# -----------------------------------------------------
# mlc
# -----------------------------------------------------

/gate/linac/daughters/name                       mlc
/gate/linac/daughters/insert                     box
/gate/mlc/setMaterial                Air
/gate/mlc/geometry/setXLength        500 mm
/gate/mlc/geometry/setYLength        500 mm
/gate/mlc/geometry/setZLength        76.0 mm 
/gate/mlc/placement/setTranslation   0.0 0.0 664.5 mm #(-335.5)
/gate/mlc/vis/setVisible           1
/gate/mlc/vis/setColor             red

/gate/mlc/daughters/name                 mlc_y0
/gate/mlc/daughters/insert               trap
/gate/mlc_y0/setMaterial              Tungsten
/gate/mlc_y0/geometry/setX1Length      160.5 mm  	
/gate/mlc_y0/geometry/setX1Length      162 mm  	
/gate/mlc_y0/geometry/setY0Length      80 mm
/gate/mlc_y0/geometry/setY2Length      80 mm
/gate/mlc_y0/geometry/setZLength      75 mm
/gate/mlc_y0/placement/setTranslation 0 0 0 cm
/gate/mlc_y0/vis/setVisible           1
/gate/mlc_y0/vis/setColor             magenta


#-------------------------mlc------------------------


# /gate/world/daughters/name            mlc_y
# /gate/world/daughters/insert          box 
# /gate/mlc_y/setMaterial                Air
# /gate/mlc_y/geometry/setX1Length        500 mm
# /gate/mlc_y/geometry/setX2Length        500 mm
# /gate/mlc_y/geometry/setYLength        500 mm
# /gate/mlc_y/geometry/setZLength        76.0 mm 
# /gate/mlc_y/placement/setTranslation   0.0 0.0 664.5 mm #(-335.5)
# /gate/mlc_y/vis/setVisible             0

# /gate/mlc_y/daughters/name              mlc_y1
# /gate/mlc_y/daughters/insert            box
# /gate/mlc_y1/setMaterial              Tungsten
# /gate/mlc_y1/geometry/setXLength      250 mm  	
# /gate/mlc_y1/geometry/setYLength      80 mm
# /gate/mlc_y1/geometry/setZLength      75 mm
# /gate/mlc_y1/placement/setTranslation 0 5 0 cm
# # /gate/jaws/placement/setRotationAxis  1 0 0
# # /gate/jaws/placement/setRotationAngle 37.5 deg
# /gate/mlc_y1/vis/setVisible           1
# /gate/mlc_y1/vis/setColor             magenta

# /gate/mlc_y/daughters/name                     mlc_y2
# /gate/mlc_y/daughters/insert                   box
# /gate/mlc_y2/setMaterial              Tungsten
# /gate/mlc_y2/geometry/setXLength      250 mm  
# /gate/mlc_y2/geometry/setYLength      80 mm
# /gate/mlc_y2/geometry/setZLength      75 mm
# /gate/mlc_y2/placement/setTranslation 0 -5 0 cm
# /gate/mlc_y2/vis/setVisible           1
# /gate/mlc_y2/vis/setColor             magenta