

# -----------------------------------------------------
# LINAC
# -----------------------------------------------------

/gate/world/daughters/name           linac
/gate/world/daughters/insert         box
/gate/linac/setMaterial              Air
/gate/linac/geometry/setXLength      0.5 m
/gate/linac/geometry/setYLength      0.5 m
/gate/linac/geometry/setZLength      0.6 m
/gate/linac/placement/setTranslation 0 0 1000 mm
/gate/linac/vis/setVisible           1
/gate/linac/vis/setColor             yellow

# -----------------------------------------------------
# TARGET
# -----------------------------------------------------

/control/execute /home/lb8075/linac/mac/linac_target.mac

# -----------------------------------------------------
# PRIMARY_COLLIMATOR
# -----------------------------------------------------

/control/execute /home/lb8075/linac/mac/linac_primary_collimator.mac


# -----------------------------------------------------
# FLATTENING_FILTER
# -----------------------------------------------------

/control/execute /home/lb8075/linac/mac/linac_flattening_filter.mac

# -----------------------------------------------------
# IONIZING_CHAMBER
# -----------------------------------------------------

/control/execute /home/lb8075/linac/mac/linac_ionizing_chamber.mac


# -----------------------------------------------------
# BACK_SCATTER_PLATE
# -----------------------------------------------------

/control/execute /home/lb8075/linac/mac/linac_back_scatter_plate.mac

# -----------------------------------------------------
# MIRROR
# -----------------------------------------------------

/control/execute /home/lb8075/linac/mac/linac_mirror.mac


# -----------------------------------------------------
# KILLING BOX: to kill particle in some regions (when they dont go in
# the good direction) and thus gain time
# -----------------------------------------------------

/gate/linac/daughters/name                      kill_box_top
/gate/linac/daughters/insert                    cylinder
/gate/kill_box_top/setMaterial                  Vacuum
/gate/kill_box_top/geometry/setRmin             0 mm
/gate/kill_box_top/geometry/setRmax             30 mm
/gate/kill_box_top/geometry/setHeight           20 mm
/gate/kill_box_top/placement/setTranslation     0.0 0.0 21 mm
/gate/kill_box_top/vis/setVisible               0

/gate/linac/daughters/name                      kill_box_bottom
/gate/linac/daughters/insert                    cylinder
/gate/kill_box_bottom/setMaterial               Vacuum
/gate/kill_box_bottom/geometry/setRmin          16 mm
/gate/kill_box_bottom/geometry/setRmax          30 mm
/gate/kill_box_bottom/geometry/setHeight        21.5 mm
/gate/kill_box_bottom/placement/setTranslation  0.0 0.0 0.25 mm
/gate/kill_box_bottom/vis/setVisible            0

/gate/linac/daughters/name                      kill_box_bottom2
/gate/linac/daughters/insert                    cylinder
/gate/kill_box_bottom2/setMaterial              Vacuum
/gate/kill_box_bottom2/geometry/setRmin         30 mm
/gate/kill_box_bottom2/geometry/setRmax         50 cm
/gate/kill_box_bottom2/geometry/setHeight       21.5 mm
/gate/kill_box_bottom2/placement/setTranslation 0.0 0.0 0.25 mm
/gate/kill_box_bottom2/vis/setVisible           0


/gate/linac/daughters/name                      kill_box_side
/gate/linac/daughters/insert                    box
/gate/kill_box_side/setMaterial              Vacuum
/gate/kill_box_side/geometry/setXLength         0.219 m
/gate/kill_box_side/geometry/setYLength         0.01 mm
/gate/kill_box_side/geometry/setZLength       0.59 m
/gate/kill_box_side/placement/setTranslation 0.0 110.0 0 mm
/gate/kill_box_side/vis/setVisible           1
/gate/kill_box_side/vis/setColor                  red

/gate/linac/daughters/name                      kill_box_side2
/gate/linac/daughters/insert                    box
/gate/kill_box_side2/setMaterial              Vacuum
/gate/kill_box_side2/geometry/setXLength         0.219 m
/gate/kill_box_side2/geometry/setYLength         0.01 mm
/gate/kill_box_side2/geometry/setZLength       0.59 m
/gate/kill_box_side2/placement/setTranslation 0.0 -110.0 0 mm
/gate/kill_box_side2/vis/setVisible           1
/gate/kill_box_side2/vis/setColor                  red

/gate/linac/daughters/name                      kill_box_side3
/gate/linac/daughters/insert                    box
/gate/kill_box_side3/setMaterial              Vacuum
/gate/kill_box_side3/geometry/setXLength         0.01 mm
/gate/kill_box_side3/geometry/setYLength         0.219 m
/gate/kill_box_side3/geometry/setZLength       0.59 m
/gate/kill_box_side3/placement/setTranslation 110.0 0.0 0 mm
/gate/kill_box_side3/vis/setVisible           1
/gate/kill_box_side3/vis/setColor                  red

/gate/linac/daughters/name                      kill_box_side4
/gate/linac/daughters/insert                    box
/gate/kill_box_side4/setMaterial              Vacuum
/gate/kill_box_side4/geometry/setXLength         0.01 mm
/gate/kill_box_side4/geometry/setYLength         0.219 m
/gate/kill_box_side4/geometry/setZLength       0.59 m
/gate/kill_box_side4/placement/setTranslation -110.0 0.0 0 mm
/gate/kill_box_side4/vis/setVisible           1
/gate/kill_box_side4/vis/setColor                  red

