# -----------------------------------------------------
# Jaws
# -----------------------------------------------------

#-------------------------MLC------------------------


/gate/world/daughters/name            mlc_y
/gate/world/daughters/insert          box 
/gate/mlc_y/setMaterial                Air
/gate/mlc_y/geometry/setXLength        500 mm
/gate/mlc_y/geometry/setYLength        500 mm
/gate/mlc_y/geometry/setZLength        76.0 mm 
/gate/mlc_y/placement/setTranslation   0.0 0.0 664.5 mm #(-335.5)
/gate/mlc_y/vis/setVisible             0

/gate/mlc_y/daughters/name              mlc_y1
/gate/mlc_y/daughters/insert            box
/gate/mlc_y1/setMaterial              Tungsten
/gate/mlc_y1/geometry/setXLength      250 mm  	
/gate/mlc_y1/geometry/setYLength      80 mm
/gate/mlc_y1/geometry/setZLength      75 mm
/gate/mlc_y1/placement/setTranslation 0 5 0 cm
# /gate/jaws/placement/setRotationAxis  1 0 0
# /gate/jaws/placement/setRotationAngle 37.5 deg
/gate/mlc_y1/vis/setVisible           1
/gate/mlc_y1/vis/setColor             magenta

/gate/mlc_y/daughters/name                     mlc_y2
/gate/mlc_y/daughters/insert                   box
/gate/mlc_y2/setMaterial              Tungsten
/gate/mlc_y2/geometry/setXLength      250 mm  
/gate/mlc_y2/geometry/setYLength      80 mm
/gate/mlc_y2/geometry/setZLength      75 mm
/gate/mlc_y2/placement/setTranslation 0 -5 0 cm
/gate/mlc_y2/vis/setVisible           1
/gate/mlc_y2/vis/setColor             magenta

#-------------------------JawsY------------------------

/gate/world/daughters/name            jaws_y
/gate/world/daughters/insert          box
/gate/jaws_y/setMaterial                Air
/gate/jaws_y/geometry/setXLength        500 mm
/gate/jaws_y/geometry/setYLength        500 mm
/gate/jaws_y/geometry/setZLength        31.0 mm 
/gate/jaws_y/placement/setTranslation   0.0 0.0 589 mm #(-411)
/gate/jaws_y/vis/setVisible             0

/gate/jaws_y/daughters/name              jaws_y1
/gate/jaws_y/daughters/insert            box
/gate/jaws_y1/setMaterial              Tungsten
/gate/jaws_y1/geometry/setXLength      250 mm  	
/gate/jaws_y1/geometry/setYLength      80 mm
/gate/jaws_y1/geometry/setZLength      30 mm
/gate/jaws_y1/placement/setTranslation 0 5 0 cm
# /gate/jaws/placement/setRotationAxis  1 0 0
# /gate/jaws/placement/setRotationAngle 37.5 deg
/gate/jaws_y1/vis/setVisible           1
/gate/jaws_y1/vis/setColor             green

/gate/jaws_y/daughters/name                     jaws_y2
/gate/jaws_y/daughters/insert                   box
/gate/jaws_y2/setMaterial              Tungsten
/gate/jaws_y2/geometry/setXLength      250 mm  
/gate/jaws_y2/geometry/setYLength      80 mm
/gate/jaws_y2/geometry/setZLength      30 mm
/gate/jaws_y2/placement/setTranslation 0 -5 0 cm
/gate/jaws_y2/vis/setVisible           1
/gate/jaws_y2/vis/setColor             green

#-------------------------JawsX------------------------

/gate/world/daughters/name            jaws_x
/gate/world/daughters/insert          box
/gate/jaws_x/setMaterial                Air
/gate/jaws_x/geometry/setXLength        500 mm
/gate/jaws_x/geometry/setYLength        500 mm
/gate/jaws_x/geometry/setZLength        79.0 mm 
/gate/jaws_x/placement/setTranslation   0.0 0.0 530 mm #(-470)
/gate/jaws_x/vis/setVisible             0

/gate/jaws_x/daughters/name              jaws_x1
/gate/jaws_x/daughters/insert            box
/gate/jaws_x1/setMaterial              Tungsten
/gate/jaws_x1/geometry/setXLength      78 mm  	
/gate/jaws_x1/geometry/setYLength      250 mm
/gate/jaws_x1/geometry/setZLength      78 mm
/gate/jaws_x1/placement/setTranslation 5 0 0 cm
# /gate/jaws/placement/setRotationAxis  1 0 0
# /gate/jaws/placement/setRotationAngle 37.5 deg
/gate/jaws_x1/vis/setVisible           1
/gate/jaws_x1/vis/setColor             red

/gate/jaws_x/daughters/name                     jaws_x2
/gate/jaws_x/daughters/insert                   box
/gate/jaws_x2/setMaterial              Tungsten
/gate/jaws_x2/geometry/setXLength      78 mm  
/gate/jaws_x2/geometry/setYLength      250 mm
/gate/jaws_x2/geometry/setZLength      78 mm
/gate/jaws_x2/placement/setTranslation -5 0 0 cm
/gate/jaws_x2/vis/setVisible           1
/gate/jaws_x2/vis/setColor             red