
#=====================================================
# VERBOSITY
#=====================================================

/control/execute mac/verbose.mac

#=====================================================
# VISUALISATION
#=====================================================

/control/execute mac/visu.mac

# =====================================================
# GEOMETRY
# =====================================================

/gate/geometry/setMaterialDatabase data/GateMaterials.db

# WORLD
/gate/world/setMaterial            Air
/gate/world/geometry/setXLength    3.0 m
/gate/world/geometry/setYLength    3.0 m
/gate/world/geometry/setZLength    3.0 m
/gate/world/vis/setVisible 1


# VIRTUAL PLANE FOR PHASE SPACE
# It should be the same geometry than PhS generation Here we add a
# "gantry" rotation. To do that easily, we define two box, on for the
# rotation (according to the isocenter=world origin), then one another
# to translation the phase-space plane to the right distance

/gate/world/daughters/name                     linacGantry
/gate/world/daughters/insert                   box
/gate/linacGantry/setMaterial                  Air
/gate/linacGantry/geometry/setXLength          1.0 mm
/gate/linacGantry/geometry/setYLength          1.0 mm
/gate/linacGantry/geometry/setZLength          1.0 mm
/gate/linacGantry/placement/setRotationAxis    0 1 0
/gate/linacGantry/placement/setRotationAngle   0 deg
/gate/linacGantry/vis/setVisible               1

/gate/linacGantry/daughters/name         linac
/gate/linacGantry/daughters/insert       box
/gate/linac/setMaterial                  Air
/gate/linac/geometry/setXLength          1.0 mm
/gate/linac/geometry/setYLength          1.0 mm
/gate/linac/geometry/setZLength          1.0 mm
/gate/linac/placement/setTranslation     0 0 1000 mm
/gate/linac/vis/setVisible               1

# /gate/geometry/setMaterialDatabase data/PreciseMaterials.db
# /control/execute mac/linac_head.mac
# /gate/linac/placement/setTranslation 0 0 1000 mm

/gate/linac/daughters/name               PhS_Plane
/gate/linac/daughters/insert             cylinder
/gate/PhS_Plane/setMaterial              Vacuum
/gate/PhS_Plane/geometry/setRmin         0 mm
/gate/PhS_Plane/geometry/setRmax         70 mm
/gate/PhS_Plane/geometry/setHeight       1 nm
/gate/PhS_Plane/placement/setTranslation 0.0 0.0 -297 mm
/gate/PhS_Plane/vis/setColor             white
/gate/PhS_Plane/vis/setVisible           1

# Jaws
/control/execute mac/linac_jaws.mac



/gate/world/daughters/name                   PhS_Plane_Two
/gate/world/daughters/insert                 box
/gate/PhS_Plane_Two/setMaterial              Vacuum
/gate/PhS_Plane_Two/geometry/setXLength      100 mm
/gate/PhS_Plane_Two/geometry/setYLength      100 mm
/gate/PhS_Plane_Two/geometry/setZLength      1 nm
/gate/PhS_Plane_Two/placement/setTranslation 0.0 0.0 471 mm #(-529)
/gate/PhS_Plane_Two/vis/setColor             cyan
/gate/PhS_Plane_Two/vis/setVisible           1

# =====================================================
# PHYSICS
# =====================================================

/gate/physics/addPhysicsList emstandard_opt3

/gate/physics/Gamma/SetCutInRegion      world 1 mm
/gate/physics/Electron/SetCutInRegion   world 1 mm
/gate/physics/Positron/SetCutInRegion   world 1 mm

# /gate/physics/Gamma/SetCutInRegion      mlc_y 0.001 mm
# /gate/physics/Electron/SetCutInRegion   mlc_y 0.001 mm
# /gate/physics/Positron/SetCutInRegion   mlc_y 0.001 mm

# /gate/physics/Gamma/SetCutInRegion      waterbox 0.5 mm
# /gate/physics/Electron/SetCutInRegion   waterbox 0.5 mm
# /gate/physics/Positron/SetCutInRegion   waterbox 0.5 mm

# /gate/physics/addProcess Compton
# /gate/physics/processes/Compton/setModel StandardModel gamma
# /gate/physics/processes/Compton/activateSplitting gamma 100

#=====================================================
# DETECTORS
#=====================================================

# ----------------------------------------------------
# the following actor regularly store the current number of
# event/track/step in a file

/gate/actor/addActor               SimulationStatisticActor stat
/gate/actor/stat/save              output/output-readPhS-stat.txt
/gate/actor/stat/saveEveryNSeconds 10

# ----------------------------------------------------
# the following actor stores 3D Dose/Edep distributions

# ----------------------------------------------------
# Phase space storage (a PhS for gamma, another for e-)

# /gate/actor/addActor                         PhaseSpaceActor PhS_g
# /gate/actor/PhS_g/attachTo                   PhS_Plane_Two
# /gate/actor/PhS_g/save 	                     output/output-lana2-PhS-g.root
# /gate/actor/PhS_g/enableParticleName         false
# /gate/actor/PhS_g/enableProductionVolume     false
# /gate/actor/PhS_g/enableProductionProcess    false
# /gate/actor/PhS_g/useVolumeFrame             true
# /gate/actor/PhS_g/addFilter                  particleFilter
# /gate/actor/PhS_g/particleFilter/addParticle gamma
# /gate/actor/PhS_g/enableZPosition            true
# #/gate/actor/PhS_g/saveEveryNSeconds          20

# /gate/actor/addActor                         PhaseSpaceActor PhS_e
# /gate/actor/PhS_e/attachTo                   PhS_Plane_Two
# /gate/actor/PhS_e/save 	                     output/output-lana2-PhS-e.root
# /gate/actor/PhS_e/enableParticleName         false
# /gate/actor/PhS_e/enableProductionVolume     false
# /gate/actor/PhS_e/enableProductionProcess    false
# /gate/actor/PhS_e/useVolumeFrame             true
# /gate/actor/PhS_e/addFilter                  particleFilter
# /gate/actor/PhS_e/particleFilter/addParticle e-
# /gate/actor/PhS_e/particleFilter/addParticle e+
# /gate/actor/PhS_e/enableZPosition            true
# /gate/actor/PhS_e/saveEveryNSeconds          20
#=====================================================
# INITIALISATION
#=====================================================

/gate/run/initialize
# /process/em/setSecBiasing compt world 10 100 MeV
# /process/em/setSecBiasing compt mlc_y2 100 100 MeV
# /process/em/setSecBiasing compt jaw_y1 100 100 MeV
# /process/em/setSecBiasing compt jaw_y2 100 100 MeV
# /process/em/setSecBiasing compt jaw_x1 100 100 MeV
# /process/em/setSecBiasing compt jaw_x2 100 100 MeV
#=====================================================
# BEAMS
#=====================================================

# Read from Phase Space files. Here we indicate the type of particle
# (gamma) because this information is not stored in the PhS to gain
# space. Moreover, we set 'useRandomSymmetry' to generate more
# particle than the number of particle in the PhS, using a Z axis
# symmetry.

/gate/source/addSource                         beam_g phaseSpace
/gate/source/beam_g/addPhaseSpaceFile          output/output-lana-PhS-gb.root
/gate/source/beam_g/setParticleType            gamma
/gate/source/beam_g/attachTo                   PhS_Plane
/gate/source/beam_g/useRandomSymmetry          true


#=====================================================
# START BEAMS
#=====================================================

/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed auto
/gate/application/noGlobalOutput

#/tracking/verbose 2

/gate/application/setTotalNumberOfPrimaries 10000
/gate/application/start


/gate/physics/processList Enabled
/gate/physics/processList Initialized
