
/vis/open OGLIQt
/vis/drawVolume
/vis/viewer/flush
/tracking/storeTrajectory             1
/vis/scene/add/trajectories
/vis/scene/endOfEventAction           accumulate 100000
/vis/viewer/set/viewpointThetaPhi 270 0

/vis/scene/add/axes            0 0 0 500 mm
/vis/scene/add/text            10 0 0 cm  20 0 0   X
/vis/scene/add/text            0 10 0 cm  20 0 0   Y
/vis/scene/add/text            0 0 10 cm  20 0 0   Z
/vis/viewer/set/auxiliaryEdge true
