#!/bin/bash 
#PBS -l walltime=01:00:00 
#PBS -j oe
#PBS -l select=1:ncpus=1
#PBS -l select=1:ncpus=1:mem=500mb
#PBS -o /work/lb8075/job_logfiles

module add apps/gate/8.2
hadd -f /work/lb8075/PhaseSpaces/Flex/PhS3DoseFromElec_100umpeak_300umBlackOut_peakMat_Aluminium_BOmat_Polyethylene_BlackOut-under-peaks/Total-Edep.root /work/lb8075/PhaseSpaces/Flex/PhS3DoseFromElec_100umpeak_300umBlackOut_peakMat_Aluminium_BOmat_Polyethylene_BlackOut-under-peaks/*Edep.root 
hadd -f /work/lb8075/PhaseSpaces/Flex/PhS3DoseFromElec_100umpeak_300umBlackOut_peakMat_Aluminium_BOmat_Polyethylene_BlackOut-under-peaks/Total-Edep-Squared.root /work/lb8075/PhaseSpaces/Flex/PhS3DoseFromElec_100umpeak_300umBlackOut_peakMat_Aluminium_BOmat_Polyethylene_BlackOut-under-peaks/*Edep-Squared.root 
hadd -f /work/lb8075/PhaseSpaces/Flex/PhS3DoseFromElec_100umpeak_300umBlackOut_peakMat_Aluminium_BOmat_Polyethylene_BlackOut-under-peaks/Total-NbOfHits.root /work/lb8075/PhaseSpaces/Flex/PhS3DoseFromElec_100umpeak_300umBlackOut_peakMat_Aluminium_BOmat_Polyethylene_BlackOut-under-peaks/*NbOfHits.root 
now=$(date) 
echo "Time of completion : $now" 
