#!/bin/bash 
#PBS -l walltime=01:00:00 
#PBS -j oe
#PBS -l select=1:ncpus=1
#PBS -l select=1:ncpus=1:mem=500mb
#PBS -o /work/lb8075/job_logfiles

module add apps/gate/8.2
hadd -f /work/lb8075/PhaseSpaces/Flex/PhS3DoseFromElec_50umpeak_300umBlackOut_peakMat_Aluminium_BOmat_Aluminium_peaks-under-BlackOut_0mm/Total-Edep.root /work/lb8075/PhaseSpaces/Flex/PhS3DoseFromElec_50umpeak_300umBlackOut_peakMat_Aluminium_BOmat_Aluminium_peaks-under-BlackOut_0mm/*Edep.root 
hadd -f /work/lb8075/PhaseSpaces/Flex/PhS3DoseFromElec_50umpeak_300umBlackOut_peakMat_Aluminium_BOmat_Aluminium_peaks-under-BlackOut_0mm/Total-Edep-Squared.root /work/lb8075/PhaseSpaces/Flex/PhS3DoseFromElec_50umpeak_300umBlackOut_peakMat_Aluminium_BOmat_Aluminium_peaks-under-BlackOut_0mm/*Edep-Squared.root 
hadd -f /work/lb8075/PhaseSpaces/Flex/PhS3DoseFromElec_50umpeak_300umBlackOut_peakMat_Aluminium_BOmat_Aluminium_peaks-under-BlackOut_0mm/Total-NbOfHits.root /work/lb8075/PhaseSpaces/Flex/PhS3DoseFromElec_50umpeak_300umBlackOut_peakMat_Aluminium_BOmat_Aluminium_peaks-under-BlackOut_0mm/*NbOfHits.root 
now=$(date) 
echo "Time of completion : $now" 
