/gate/verbose Physic 1
/gate/verbose Cuts 1
/gate/verbose SD 0
/gate/verbose Actions 0
/gate/verbose Actor 0
/gate/verbose Step 0
/gate/verbose Error 1
/gate/verbose Warning 1
/gate/verbose Output 0
/gate/verbose Beam 0
/gate/verbose Volume 0
/gate/verbose Image 0
/gate/verbose Geometry 0
/gate/verbose Core 0

/gate/geometry/setMaterialDatabase GateMaterials.db
/gate/world/setMaterial Air
/gate/world/geometry/setXLength 1 m
/gate/world/geometry/setYLength 1 m
/gate/world/geometry/setZLength 2.5 m
/gate/geometry/setMaterialDatabase LinacMaterials.db
/gate/world/daughters/name linac
/gate/world/daughters/insert box
/gate/linac/setMaterial Air
/gate/linac/geometry/setXLength 0.5 m
/gate/linac/geometry/setYLength 0.5 m
/gate/linac/geometry/setZLength 0.8 m
/gate/linac/placement/setTranslation 0 0 0 mm
/gate/linac/vis/setVisible 1
/gate/linac/vis/setColor yellow
/gate/linac/daughters/name target_support
/gate/linac/daughters/insert cylinder
/gate/target_support/setMaterial Air
/gate/target_support/geometry/setRmin 0 mm
/gate/target_support/geometry/setRmax 15 mm
/gate/target_support/geometry/setHeight 11 mm
/gate/target_support/placement/setTranslation 0.0 0.0 -5 mm
/gate/target_support/vis/setVisible 0
/gate/target_support/daughters/name target
/gate/target_support/daughters/insert cylinder
/gate/target/setMaterial AcceleratorTargetMaterial
/gate/target/geometry/setRmin 0 mm
/gate/target/geometry/setRmax 2.70 mm
/gate/target/geometry/setHeight 1.00 mm
/gate/target/placement/setTranslation 0 0 +5 mm
/gate/target/vis/setColor red
/gate/target/vis/setVisible 1
/gate/target_support/daughters/name target_support_top
/gate/target_support/daughters/insert cylinder
/gate/target_support_top/setMaterial Copper
/gate/target_support_top/geometry/setRmin 2.70 mm
/gate/target_support_top/geometry/setRmax 15 mm
/gate/target_support_top/geometry/setHeight 1.00 mm
/gate/target_support_top/placement/setTranslation 0.0 0.0 +5.0 mm
/gate/target_support_top/vis/setColor green
/gate/target_support_top/vis/setVisible 1
/gate/target_support/daughters/name target_support_bottom
/gate/target_support/daughters/insert cylinder
/gate/target_support_bottom/setMaterial Copper
/gate/target_support_bottom/geometry/setRmin 0 mm
/gate/target_support_bottom/geometry/setRmax 15 mm
/gate/target_support_bottom/geometry/setHeight 10 mm
/gate/target_support_bottom/placement/setTranslation 0.0 0.0 -0.5 mm
/gate/target_support_bottom/vis/setColor green
/gate/target_support_bottom/vis/setVisible 1

/gate/linac/daughters/name primary_collimator
/gate/linac/daughters/insert cone
/gate/primary_collimator/setMaterial AcceleratorPrimaryCollimatorMaterial
/gate/primary_collimator/geometry/setRmin2 6.45 mm
/gate/primary_collimator/geometry/setRmax2 82 mm
/gate/primary_collimator/geometry/setRmin1 31.45 mm
/gate/primary_collimator/geometry/setRmax1 82 mm
/gate/primary_collimator/geometry/setHeight 101 mm
/gate/primary_collimator/placement/setTranslation 0 0 -65.5 mm
/gate/primary_collimator/vis/setColor blue
/gate/primary_collimator/vis/setVisible 1

/gate/linac/daughters/name flattening_filter
/gate/linac/daughters/insert cylinder
/gate/flattening_filter/setMaterial Air
/gate/flattening_filter/geometry/setRmin 0 mm
/gate/flattening_filter/geometry/setRmax 40 mm
/gate/flattening_filter/geometry/setHeight 24.1 mm
/gate/flattening_filter/placement/setTranslation 0.0 0.0 -146.05 mm
/gate/flattening_filter/vis/setVisible 0
/gate/flattening_filter/daughters/name flattening_filter_cone1
/gate/flattening_filter/daughters/insert cone
/gate/flattening_filter_cone1/setMaterial AcceleratorFlatteningFilter
/gate/flattening_filter_cone1/geometry/setRmin2 0 mm
/gate/flattening_filter_cone1/geometry/setRmax2 0.001 mm
/gate/flattening_filter_cone1/geometry/setRmin1 0 mm
/gate/flattening_filter_cone1/geometry/setRmax1 5.45 mm
/gate/flattening_filter_cone1/geometry/setHeight 3.40 mm
/gate/flattening_filter_cone1/placement/setTranslation 0.0 0.0 +10.35 mm
/gate/flattening_filter_cone1/vis/setColor yellow
/gate/flattening_filter_cone1/vis/setVisible 1
/gate/flattening_filter/daughters/name flattening_filter_cone2
/gate/flattening_filter/daughters/insert cone
/gate/flattening_filter_cone2/setMaterial AcceleratorFlatteningFilter
/gate/flattening_filter_cone2/geometry/setRmin2 0 mm
/gate/flattening_filter_cone2/geometry/setRmax2 5.45 mm
/gate/flattening_filter_cone2/geometry/setRmin1 0 mm
/gate/flattening_filter_cone2/geometry/setRmax1 9.00 mm
/gate/flattening_filter_cone2/geometry/setHeight 2.70 mm
/gate/flattening_filter_cone2/placement/setTranslation 0.0 0.0 +7.3 mm
/gate/flattening_filter_cone2/vis/setColor yellow
/gate/flattening_filter_cone2/vis/setVisible 1
/gate/flattening_filter/daughters/name flattening_filter_cone3
/gate/flattening_filter/daughters/insert cone
/gate/flattening_filter_cone3/setMaterial AcceleratorFlatteningFilter
/gate/flattening_filter_cone3/geometry/setRmin2 0 mm
/gate/flattening_filter_cone3/geometry/setRmax2 9.00 mm
/gate/flattening_filter_cone3/geometry/setRmin1 0 mm
/gate/flattening_filter_cone3/geometry/setRmax1 14.50 mm
/gate/flattening_filter_cone3/geometry/setHeight 4.90 mm
/gate/flattening_filter_cone3/placement/setTranslation 0.0 0.0 +3.5 mm
/gate/flattening_filter_cone3/vis/setColor yellow
/gate/flattening_filter_cone3/vis/setVisible 1
/gate/flattening_filter/daughters/name flattening_filter_cone4
/gate/flattening_filter/daughters/insert cone
/gate/flattening_filter_cone4/setMaterial AcceleratorFlatteningFilter
/gate/flattening_filter_cone4/geometry/setRmin2 0 mm
/gate/flattening_filter_cone4/geometry/setRmax2 14.50 mm
/gate/flattening_filter_cone4/geometry/setRmin1 0 mm
/gate/flattening_filter_cone4/geometry/setRmax1 22.50 mm
/gate/flattening_filter_cone4/geometry/setHeight 5.50 mm
/gate/flattening_filter_cone4/placement/setTranslation 0.0 0.0 -1.7 mm
/gate/flattening_filter_cone4/vis/setColor yellow
/gate/flattening_filter_cone4/vis/setVisible 1
/gate/flattening_filter/daughters/name flattening_filter_cone5
/gate/flattening_filter/daughters/insert cone
/gate/flattening_filter_cone5/setMaterial AcceleratorFlatteningFilter
/gate/flattening_filter_cone5/geometry/setRmin2 0 mm
/gate/flattening_filter_cone5/geometry/setRmax2 22.50 mm
/gate/flattening_filter_cone5/geometry/setRmin1 0 mm
/gate/flattening_filter_cone5/geometry/setRmax1 32.50 mm
/gate/flattening_filter_cone5/geometry/setHeight 5.60 mm
/gate/flattening_filter_cone5/placement/setTranslation 0.0 0.0 -7.25 mm
/gate/flattening_filter_cone5/vis/setColor yellow
/gate/flattening_filter_cone5/vis/setVisible 1
/gate/flattening_filter/daughters/name flattening_filter_cone6
/gate/flattening_filter/daughters/insert cone
/gate/flattening_filter_cone6/setMaterial AcceleratorFlatteningFilter
/gate/flattening_filter_cone6/geometry/setRmin2 0 mm
/gate/flattening_filter_cone6/geometry/setRmax2 38.50 mm
/gate/flattening_filter_cone6/geometry/setRmin1 0 mm
/gate/flattening_filter_cone6/geometry/setRmax1 38.50 mm
/gate/flattening_filter_cone6/geometry/setHeight 2.0 mm
/gate/flattening_filter_cone6/placement/setTranslation 0.0 0.0 -11.05 mm
/gate/flattening_filter_cone6/vis/setColor yellow
/gate/flattening_filter_cone6/vis/setVisible 1

/gate/linac/daughters/name ionizing_chamber
/gate/linac/daughters/insert cylinder
/gate/ionizing_chamber/setMaterial Air
/gate/ionizing_chamber/geometry/setRmin 0 mm
/gate/ionizing_chamber/geometry/setRmax 45 mm
/gate/ionizing_chamber/geometry/setHeight 9.28 mm
/gate/ionizing_chamber/placement/setTranslation 0.0 0.0 -169 mm
/gate/ionizing_chamber/vis/setVisible 1
/gate/ionizing_chamber/vis/setColor cyan
/gate/ionizing_chamber/daughters/name ionizing_chamber_mylar_1ayer1
/gate/ionizing_chamber/daughters/insert cylinder
/gate/ionizing_chamber_mylar_1ayer1/setMaterial Mylar
/gate/ionizing_chamber_mylar_1ayer1/geometry/setRmin 0 mm
/gate/ionizing_chamber_mylar_1ayer1/geometry/setRmax 45 mm
/gate/ionizing_chamber_mylar_1ayer1/geometry/setHeight 0.012 mm
/gate/ionizing_chamber_mylar_1ayer1/placement/setTranslation 0.0 0.0 -2.634 mm
/gate/ionizing_chamber/daughters/name ionizing_chamber_carbon_1ayer1
/gate/ionizing_chamber/daughters/insert cylinder
/gate/ionizing_chamber_carbon_1ayer1/setMaterial Carbon
/gate/ionizing_chamber_carbon_1ayer1/geometry/setRmin 0 mm
/gate/ionizing_chamber_carbon_1ayer1/geometry/setRmax 45 mm
/gate/ionizing_chamber_carbon_1ayer1/geometry/setHeight 0.000150 mm
/gate/ionizing_chamber_carbon_1ayer1/placement/setTranslation 0.0 0.0 -2.627925 mm
/gate/ionizing_chamber/daughters/name ionizing_chamber_mylar_1ayer2
/gate/ionizing_chamber/daughters/insert cylinder
/gate/ionizing_chamber_mylar_1ayer2/setMaterial Mylar
/gate/ionizing_chamber_mylar_1ayer2/geometry/setRmin 0 mm
/gate/ionizing_chamber_mylar_1ayer2/geometry/setRmax 45 mm
/gate/ionizing_chamber_mylar_1ayer2/geometry/setHeight 0.012 mm
/gate/ionizing_chamber_mylar_1ayer2/placement/setTranslation 0.0 0.0 -0.434 mm
/gate/ionizing_chamber/daughters/name ionizing_chamber_carbon_1ayer2
/gate/ionizing_chamber/daughters/insert cylinder
/gate/ionizing_chamber_carbon_1ayer2/setMaterial Carbon
/gate/ionizing_chamber_carbon_1ayer2/geometry/setRmin 0 mm
/gate/ionizing_chamber_carbon_1ayer2/geometry/setRmax 45 mm
/gate/ionizing_chamber_carbon_1ayer2/geometry/setHeight 0.000150 mm
/gate/ionizing_chamber_carbon_1ayer2/placement/setTranslation 0.0 0.0 -0.427925 mm
/gate/ionizing_chamber/daughters/name ionizing_chamber_mylar_1ayer3
/gate/ionizing_chamber/daughters/insert cylinder
/gate/ionizing_chamber_mylar_1ayer3/setMaterial Mylar
/gate/ionizing_chamber_mylar_1ayer3/geometry/setRmin 0 mm
/gate/ionizing_chamber_mylar_1ayer3/geometry/setRmax 45 mm
/gate/ionizing_chamber_mylar_1ayer3/geometry/setHeight 0.012 mm
/gate/ionizing_chamber_mylar_1ayer3/placement/setTranslation 0.0 0.0 +0.566 mm
/gate/ionizing_chamber/daughters/name ionizing_chamber_carbon_1ayer3
/gate/ionizing_chamber/daughters/insert cylinder
/gate/ionizing_chamber_carbon_1ayer3/setMaterial Carbon
/gate/ionizing_chamber_carbon_1ayer3/geometry/setRmin 0 mm
/gate/ionizing_chamber_carbon_1ayer3/geometry/setRmax 45 mm
/gate/ionizing_chamber_carbon_1ayer3/geometry/setHeight 0.000150 mm
/gate/ionizing_chamber_carbon_1ayer3/placement/setTranslation 0.0 0.0 +0.572075 mm
/gate/ionizing_chamber/daughters/name ionizing_chamber_mylar_1ayer4
/gate/ionizing_chamber/daughters/insert cylinder
/gate/ionizing_chamber_mylar_1ayer4/setMaterial Mylar
/gate/ionizing_chamber_mylar_1ayer4/geometry/setRmin 0 mm
/gate/ionizing_chamber_mylar_1ayer4/geometry/setRmax 45 mm
/gate/ionizing_chamber_mylar_1ayer4/geometry/setHeight 0.012 mm
/gate/ionizing_chamber_mylar_1ayer4/placement/setTranslation 0.0 0.0 +1.566 mm
/gate/ionizing_chamber/daughters/name ionizing_chamber_carbon_1ayer4
/gate/ionizing_chamber/daughters/insert cylinder
/gate/ionizing_chamber_carbon_1ayer4/setMaterial Carbon
/gate/ionizing_chamber_carbon_1ayer4/geometry/setRmin 0 mm
/gate/ionizing_chamber_carbon_1ayer4/geometry/setRmax 45 mm
/gate/ionizing_chamber_carbon_1ayer4/geometry/setHeight 0.000150 mm
/gate/ionizing_chamber_carbon_1ayer4/placement/setTranslation 0.0 0.0 +1.572075 mm
/gate/ionizing_chamber/daughters/name ionizing_chamber_mylar_1ayer5
/gate/ionizing_chamber/daughters/insert cylinder
/gate/ionizing_chamber_mylar_1ayer5/setMaterial Mylar
/gate/ionizing_chamber_mylar_1ayer5/geometry/setRmin 0 mm
/gate/ionizing_chamber_mylar_1ayer5/geometry/setRmax 45 mm
/gate/ionizing_chamber_mylar_1ayer5/geometry/setHeight 0.012 mm
/gate/ionizing_chamber_mylar_1ayer5/placement/setTranslation 0.0 0.0 +2.566 mm
/gate/ionizing_chamber/daughters/name ionizing_chamber_carbon_1ayer5
/gate/ionizing_chamber/daughters/insert cylinder
/gate/ionizing_chamber_carbon_1ayer5/setMaterial Carbon
/gate/ionizing_chamber_carbon_1ayer5/geometry/setRmin 0 mm
/gate/ionizing_chamber_carbon_1ayer5/geometry/setRmax 45 mm
/gate/ionizing_chamber_carbon_1ayer5/geometry/setHeight 0.000150 mm
/gate/ionizing_chamber_carbon_1ayer5/placement/setTranslation 0.0 0.0 +2.572075 mm
/gate/ionizing_chamber/daughters/name ionizing_chamber_mylar_1ayer6
/gate/ionizing_chamber/daughters/insert cylinder
/gate/ionizing_chamber_mylar_1ayer6/setMaterial Mylar
/gate/ionizing_chamber_mylar_1ayer6/geometry/setRmin 0 mm
/gate/ionizing_chamber_mylar_1ayer6/geometry/setRmax 45 mm
/gate/ionizing_chamber_mylar_1ayer6/geometry/setHeight 0.012 mm
/gate/ionizing_chamber_mylar_1ayer6/placement/setTranslation 0.0 0.0 +3.566 mm
/gate/ionizing_chamber/daughters/name ionizing_chamber_carbon_1ayer6
/gate/ionizing_chamber/daughters/insert cylinder
/gate/ionizing_chamber_carbon_1ayer6/setMaterial Carbon
/gate/ionizing_chamber_carbon_1ayer6/geometry/setRmin 0 mm
/gate/ionizing_chamber_carbon_1ayer6/geometry/setRmax 45 mm
/gate/ionizing_chamber_carbon_1ayer6/geometry/setHeight 0.000150 mm
/gate/ionizing_chamber_carbon_1ayer6/placement/setTranslation 0.0 0.0 +3.572075 mm

/gate/linac/daughters/name back_scatter_plate
/gate/linac/daughters/insert box
/gate/back_scatter_plate/setMaterial Aluminium
/gate/back_scatter_plate/geometry/setXLength 116 mm
/gate/back_scatter_plate/geometry/setYLength 84 mm
/gate/back_scatter_plate/geometry/setZLength 3 mm
/gate/back_scatter_plate/placement/setTranslation 0.0 0.0 -183 mm
/gate/back_scatter_plate/vis/setVisible 1
/gate/back_scatter_plate/vis/setColor red

/gate/linac/daughters/name mirror
/gate/linac/daughters/insert box
/gate/mirror/setMaterial Air
/gate/mirror/geometry/setXLength 137 mm
/gate/mirror/geometry/setYLength 137 mm
/gate/mirror/geometry/setZLength 1.5 mm
/gate/mirror/placement/setTranslation 0.0 0.0 -225 mm
/gate/mirror/placement/setRotationAxis 1 0 0
/gate/mirror/placement/setRotationAngle 37.5 deg
/gate/mirror/vis/setVisible 0
/gate/mirror/daughters/name mirror_mylar
/gate/mirror/daughters/insert box
/gate/mirror_mylar/setMaterial Mylar
/gate/mirror_mylar/geometry/setXLength 110 mm   
/gate/mirror_mylar/geometry/setYLength 110 mm
/gate/mirror_mylar/geometry/setZLength 0.0012 mm
/gate/mirror_mylar/placement/setTranslation 0 0 +0.15 mm
/gate/mirror_mylar/vis/setVisible 1
/gate/mirror_mylar/vis/setColor blue
/gate/mirror/daughters/name mirror_aluminium
/gate/mirror/daughters/insert box
/gate/mirror_aluminium/setMaterial Aluminium
/gate/mirror_aluminium/geometry/setXLength 110 mm
/gate/mirror_aluminium/geometry/setYLength 110 mm
/gate/mirror_aluminium/geometry/setZLength 0.0003 mm
/gate/mirror_aluminium/placement/setTranslation 0 0 -0.6 mm
/gate/mirror_aluminium/vis/setVisible 1
/gate/mirror_aluminium/vis/setColor blue

/gate/linac/daughters/name kill_box_top
/gate/linac/daughters/insert cylinder
/gate/kill_box_top/setMaterial Vacuum
/gate/kill_box_top/geometry/setRmin 0 mm
/gate/kill_box_top/geometry/setRmax 30 mm
/gate/kill_box_top/geometry/setHeight 20 mm
/gate/kill_box_top/placement/setTranslation 0.0 0.0 21 mm
/gate/kill_box_top/vis/setVisible 0
/gate/linac/daughters/name kill_box_bottom
/gate/linac/daughters/insert cylinder
/gate/kill_box_bottom/setMaterial Vacuum
/gate/kill_box_bottom/geometry/setRmin 16 mm
/gate/kill_box_bottom/geometry/setRmax 30 mm
/gate/kill_box_bottom/geometry/setHeight 21.5 mm
/gate/kill_box_bottom/placement/setTranslation 0.0 0.0 0.25 mm
/gate/kill_box_bottom/vis/setVisible 0
/gate/linac/daughters/name kill_box_bottom2
/gate/linac/daughters/insert cylinder
/gate/kill_box_bottom2/setMaterial Vacuum
/gate/kill_box_bottom2/geometry/setRmin 30 mm
/gate/kill_box_bottom2/geometry/setRmax 50 cm
/gate/kill_box_bottom2/geometry/setHeight 21.5 mm
/gate/kill_box_bottom2/placement/setTranslation 0.0 0.0 0.25 mm
/gate/kill_box_bottom2/vis/setVisible 0

/gate/linac/daughters/name PhS_Plane
/gate/linac/daughters/insert cylinder
/gate/PhS_Plane/setMaterial Vacuum
/gate/PhS_Plane/geometry/setRmin 0 mm
/gate/PhS_Plane/geometry/setRmax 40 mm
/gate/PhS_Plane/geometry/setHeight 1 nm
/gate/PhS_Plane/placement/setTranslation 0.0 0.0 -297 mm
/gate/PhS_Plane/vis/setColor white
/gate/PhS_Plane/vis/setVisible 1
/gate/physics/addPhysicsList emstandard_opt3
/gate/physics/Gamma/SetCutInRegion world 1 mm
/gate/physics/Electron/SetCutInRegion world 1 mm
/gate/physics/Positron/SetCutInRegion world 1 mm
/gate/physics/Gamma/SetCutInRegion primary_collimator 0.5 mm
/gate/physics/Electron/SetCutInRegion primary_collimator 0.5 mm
/gate/physics/Positron/SetCutInRegion primary_collimator 0.5 mm
/gate/physics/Gamma/SetCutInRegion ionizing_chamber 0.5 mm
/gate/physics/Electron/SetCutInRegion ionizing_chamber 0.5 mm
/gate/physics/Positron/SetCutInRegion ionizing_chamber 0.5 mm
/gate/physics/Gamma/SetCutInRegion back_scatter_plate 0.5 mm
/gate/physics/Electron/SetCutInRegion back_scatter_plate 0.5 mm
/gate/physics/Positron/SetCutInRegion back_scatter_plate 0.5 mm
/gate/physics/Gamma/SetCutInRegion mirror 0.5 mm
/gate/physics/Electron/SetCutInRegion mirror 0.5 mm
/gate/physics/Positron/SetCutInRegion mirror 0.5 mm
/gate/physics/addProcess Compton
/gate/physics/processes/Compton/setModel StandardModel gamma
/gate/physics/processes/Compton/activateSplitting gamma 50
/gate/physics/processes/Compton/addFilter volumeFilter secondaries
/gate/physics/processes/Compton/secondaries/volumeFilter/addVolume flattening_filter
/gate/physics/processList Enabled
/gate/physics/processList Initialized
/gate/actor/addActor KillActor killer0
/gate/actor/killer0/attachTo kill_box_top
/gate/actor/addActor KillActor killer1
/gate/actor/killer1/attachTo kill_box_bottom
/gate/actor/addActor KillActor killer2
/gate/actor/killer2/attachTo kill_box_bottom2
/gate/actor/addActor PhaseSpaceActor PhS_g
/gate/actor/PhS_g/attachTo PhS_Plane
/gate/actor/PhS_g/save   output-lana-PhS1-g1108.root
/gate/actor/PhS_g/enableParticleName false
/gate/actor/PhS_g/enableProductionVolume true
/gate/actor/PhS_g/enableProductionProcess true
/gate/actor/PhS_g/useVolumeFrame true
/gate/actor/PhS_g/addFilter particleFilter
/gate/actor/PhS_g/particleFilter/addParticle gamma
/gate/actor/PhS_g/enableZPosition true
/gate/actor/addActor PhaseSpaceActor PhS_e
/gate/actor/PhS_e/attachTo PhS_Plane
/gate/actor/PhS_e/save   output-lana-PhS1-e1108.root
/gate/actor/PhS_e/enableParticleName false
/gate/actor/PhS_e/enableProductionVolume true
/gate/actor/PhS_e/enableProductionProcess true
/gate/actor/PhS_e/useVolumeFrame true
/gate/actor/PhS_e/addFilter particleFilter
/gate/actor/PhS_e/particleFilter/addParticle e-
/gate/actor/PhS_e/particleFilter/addParticle e+
/gate/actor/PhS_e/enableZPosition true
/gate/run/initialize
/process/em/setSecBiasing eBrem target 50 100 MeV
/gate/source/addSource mybeam gps
/gate/source/mybeam/gps/particle e-
/gate/source/mybeam/gps/pos/type Beam
/gate/source/mybeam/gps/pos/rot1 0 1 0
/gate/source/mybeam/gps/pos/rot2 1 0 0
/gate/source/mybeam/gps/pos/shape Circle
/gate/source/mybeam/gps/pos/centre 0. 0. 0.6 mm
/gate/source/mybeam/gps/pos/sigma_x 1.274 mm
/gate/source/mybeam/gps/pos/sigma_y 1.274 mm
/gate/source/mybeam/gps/ang/rot1 1 0 0
/gate/source/mybeam/gps/ang/rot2 0 1 0
/gate/source/mybeam/gps/ang/type beam1d
/gate/source/mybeam/gps/ang/sigma_r 0 deg
/gate/source/mybeam/gps/ene/type Gauss
/gate/source/mybeam/gps/ene/mono 6.7 MeV
/gate/source/mybeam/gps/ene/sigma 0.077 MeV
/gate/source/mybeam/gps/direction 0 0 -1
/gate/random/setEngineName MersenneTwister

/gate/application/noGlobalOutput
/gate/application/setTotalNumberOfPrimaries 10000000
/gate/random/setEngineSeed 4205074996300581898
/gate/application/setTimeStart 0. s
/gate/application/addSlice     1. s
/gate/application/startDAQCluster 0 1 0 s
