/gate/verbose Physic 1
/gate/verbose Cuts 1
/gate/verbose SD 0
/gate/verbose Actions 0
/gate/verbose Actor 0
/gate/verbose Step 0
/gate/verbose Error 1
/gate/verbose Warning 1
/gate/verbose Output 0
/gate/verbose Beam 0
/gate/verbose Volume 0
/gate/verbose Image 0
/gate/verbose Geometry 0
/gate/verbose Core 0

/gate/geometry/setMaterialDatabase GateMaterials.db
/gate/world/setMaterial Air
/gate/world/geometry/setXLength 0.80 m
/gate/world/geometry/setYLength 0.80 m
/gate/world/geometry/setZLength 2.1 m
/gate/world/vis/setVisible 0
/gate/world/daughters/name linacGantry
/gate/world/daughters/insert box
/gate/linacGantry/setMaterial Air
/gate/linacGantry/geometry/setXLength 1.0 mm
/gate/linacGantry/geometry/setYLength 1.0 mm
/gate/linacGantry/geometry/setZLength 1.0 mm
/gate/linacGantry/placement/setRotationAxis 0 1 0
/gate/linacGantry/placement/setRotationAngle 0 deg
/gate/linacGantry/vis/setVisible 0
/gate/linacGantry/daughters/name linac
/gate/linacGantry/daughters/insert box
/gate/linac/setMaterial Air
/gate/linac/geometry/setXLength 1.0 mm
/gate/linac/geometry/setYLength 1.0 mm
/gate/linac/geometry/setZLength 1.0 mm
/gate/linac/placement/setTranslation 0 0 1000 mm
/gate/linac/vis/setVisible 0
/gate/linac/daughters/name PhS_Plane
/gate/linac/daughters/insert cylinder
/gate/PhS_Plane/setMaterial Vacuum
/gate/PhS_Plane/geometry/setRmin 0 mm
/gate/PhS_Plane/geometry/setRmax 70 mm
/gate/PhS_Plane/geometry/setHeight 1 nm
/gate/PhS_Plane/placement/setTranslation 0.0 0.0 -297 mm
/gate/PhS_Plane/vis/setColor white
/gate/PhS_Plane/vis/setVisible 0
/gate/world/daughters/name mlc_system
/gate/world/daughters/insert box
/gate/mlc_system/setMaterial Air
/gate/mlc_system/geometry/setXLength 800 mm
/gate/mlc_system/geometry/setYLength 800 mm
/gate/mlc_system/geometry/setZLength 76.0 mm
/gate/mlc_system/placement/setTranslation 0.0 0.0 664.5 mm
/gate/mlc_system/vis/setVisible 0
/gate/mlc_system/vis/setColor green
/gate/mlc_system/daughters/name mlc_leaf
/gate/mlc_system/daughters/insert box
/gate/mlc_leaf/setMaterial Air
/gate/mlc_leaf/geometry/setXLength 400 mm
/gate/mlc_leaf/geometry/setYLength 3 mm
/gate/mlc_leaf/geometry/setZLength 75 mm
/gate/mlc_leaf/placement/setTranslation -200.0 0.0 0.0 mm
/gate/mlc_leaf/vis/setVisible 0
/gate/mlc_leaf/vis/setColor blue
/gate/mlc_leaf/daughters/name mlc_y0
/gate/mlc_leaf/daughters/insert wedge
/gate/mlc_y0/setMaterial Tungsten
/gate/mlc_y0/geometry/setNarrowerXLength 163.5 mm
/gate/mlc_y0/geometry/setXLength 164.5 mm
/gate/mlc_y0/geometry/setYLength 5 mm
/gate/mlc_y0/geometry/setZLength 3 mm
/gate/mlc_y0/placement/setTranslation 98.725 0 30 mm
/gate/mlc_y0/placement/setRotationAxis 1 0 0
/gate/mlc_y0/placement/setRotationAngle 90 deg
/gate/mlc_y0/vis/setVisible 0
/gate/mlc_y0/vis/setColor magenta
/gate/mlc_leaf/daughters/name mlc_y1
/gate/mlc_leaf/daughters/insert wedge
/gate/mlc_y1/setMaterial Tungsten
/gate/mlc_y1/geometry/setNarrowerXLength 164.5 mm
/gate/mlc_y1/geometry/setXLength 165.4 mm
/gate/mlc_y1/geometry/setYLength 5 mm
/gate/mlc_y1/geometry/setZLength 3 mm
/gate/mlc_y1/placement/setTranslation 99.19999999999999 0 25 mm
/gate/mlc_y1/placement/setRotationAxis 1 0 0
/gate/mlc_y1/placement/setRotationAngle 90 deg
/gate/mlc_y1/vis/setVisible 0
/gate/mlc_y1/vis/setColor magenta
/gate/mlc_leaf/daughters/name mlc_y2
/gate/mlc_leaf/daughters/insert wedge
/gate/mlc_y2/setMaterial Tungsten
/gate/mlc_y2/geometry/setNarrowerXLength 165.4 mm
/gate/mlc_y2/geometry/setXLength 166.1 mm
/gate/mlc_y2/geometry/setYLength 5 mm
/gate/mlc_y2/geometry/setZLength 3 mm
/gate/mlc_y2/placement/setTranslation 99.6 0 20 mm
/gate/mlc_y2/placement/setRotationAxis 1 0 0
/gate/mlc_y2/placement/setRotationAngle 90 deg
/gate/mlc_y2/vis/setVisible 0
/gate/mlc_y2/vis/setColor magenta
/gate/mlc_leaf/daughters/name mlc_y3
/gate/mlc_leaf/daughters/insert wedge
/gate/mlc_y3/setMaterial Tungsten
/gate/mlc_y3/geometry/setNarrowerXLength 166.1 mm
/gate/mlc_y3/geometry/setXLength 166.5 mm
/gate/mlc_y3/geometry/setYLength 5 mm
/gate/mlc_y3/geometry/setZLength 3 mm
/gate/mlc_y3/placement/setTranslation 99.875 0 15 mm
/gate/mlc_y3/placement/setRotationAxis 1 0 0
/gate/mlc_y3/placement/setRotationAngle 90 deg
/gate/mlc_y3/vis/setVisible 0
/gate/mlc_y3/vis/setColor magenta
/gate/mlc_leaf/daughters/name mlc_y4
/gate/mlc_leaf/daughters/insert wedge
/gate/mlc_y4/setMaterial Tungsten
/gate/mlc_y4/geometry/setNarrowerXLength 166.5 mm
/gate/mlc_y4/geometry/setXLength 166.9 mm
/gate/mlc_y4/geometry/setYLength 5 mm
/gate/mlc_y4/geometry/setZLength 3 mm
/gate/mlc_y4/placement/setTranslation 100.07499999999999 0 10 mm
/gate/mlc_y4/placement/setRotationAxis 1 0 0
/gate/mlc_y4/placement/setRotationAngle 90 deg
/gate/mlc_y4/vis/setVisible 0
/gate/mlc_y4/vis/setColor magenta
/gate/mlc_leaf/daughters/name mlc_y5
/gate/mlc_leaf/daughters/insert wedge
/gate/mlc_y5/setMaterial Tungsten
/gate/mlc_y5/geometry/setNarrowerXLength 166.9 mm
/gate/mlc_y5/geometry/setXLength 167.1 mm
/gate/mlc_y5/geometry/setYLength 5 mm
/gate/mlc_y5/geometry/setZLength 3 mm
/gate/mlc_y5/placement/setTranslation 100.225 0 5 mm
/gate/mlc_y5/placement/setRotationAxis 1 0 0
/gate/mlc_y5/placement/setRotationAngle 90 deg
/gate/mlc_y5/vis/setVisible 0
/gate/mlc_y5/vis/setColor magenta
/gate/mlc_leaf/daughters/name mlc_y6
/gate/mlc_leaf/daughters/insert wedge
/gate/mlc_y6/setMaterial Tungsten
/gate/mlc_y6/geometry/setNarrowerXLength 167.1 mm
/gate/mlc_y6/geometry/setXLength 166.9 mm
/gate/mlc_y6/geometry/setYLength 5 mm
/gate/mlc_y6/geometry/setZLength 3 mm
/gate/mlc_y6/placement/setTranslation 100.225 0 0 mm
/gate/mlc_y6/placement/setRotationAxis 1 0 0
/gate/mlc_y6/placement/setRotationAngle 90 deg
/gate/mlc_y6/vis/setVisible 0
/gate/mlc_y6/vis/setColor magenta
/gate/mlc_leaf/daughters/name mlc_y7
/gate/mlc_leaf/daughters/insert wedge
/gate/mlc_y7/setMaterial Tungsten
/gate/mlc_y7/geometry/setNarrowerXLength 166.9 mm
/gate/mlc_y7/geometry/setXLength 166.6 mm
/gate/mlc_y7/geometry/setYLength 5 mm
/gate/mlc_y7/geometry/setZLength 3 mm
/gate/mlc_y7/placement/setTranslation 100.1 0 -5 mm
/gate/mlc_y7/placement/setRotationAxis 1 0 0
/gate/mlc_y7/placement/setRotationAngle 90 deg
/gate/mlc_y7/vis/setVisible 0
/gate/mlc_y7/vis/setColor magenta
/gate/mlc_leaf/daughters/name mlc_y8
/gate/mlc_leaf/daughters/insert wedge
/gate/mlc_y8/setMaterial Tungsten
/gate/mlc_y8/geometry/setNarrowerXLength 166.6 mm
/gate/mlc_y8/geometry/setXLength 166.2 mm
/gate/mlc_y8/geometry/setYLength 5 mm
/gate/mlc_y8/geometry/setZLength 3 mm
/gate/mlc_y8/placement/setTranslation 99.92499999999998 0 -10 mm
/gate/mlc_y8/placement/setRotationAxis 1 0 0
/gate/mlc_y8/placement/setRotationAngle 90 deg
/gate/mlc_y8/vis/setVisible 0
/gate/mlc_y8/vis/setColor magenta
/gate/mlc_leaf/daughters/name mlc_y9
/gate/mlc_leaf/daughters/insert wedge
/gate/mlc_y9/setMaterial Tungsten
/gate/mlc_y9/geometry/setNarrowerXLength 166.2 mm
/gate/mlc_y9/geometry/setXLength 165.8 mm
/gate/mlc_y9/geometry/setYLength 5 mm
/gate/mlc_y9/geometry/setZLength 3 mm
/gate/mlc_y9/placement/setTranslation 99.725 0 -15 mm
/gate/mlc_y9/placement/setRotationAxis 1 0 0
/gate/mlc_y9/placement/setRotationAngle 90 deg
/gate/mlc_y9/vis/setVisible 0
/gate/mlc_y9/vis/setColor magenta
/gate/mlc_leaf/daughters/name mlc_y10
/gate/mlc_leaf/daughters/insert wedge
/gate/mlc_y10/setMaterial Tungsten
/gate/mlc_y10/geometry/setNarrowerXLength 165.8 mm
/gate/mlc_y10/geometry/setXLength 165.2 mm
/gate/mlc_y10/geometry/setYLength 5 mm
/gate/mlc_y10/geometry/setZLength 3 mm
/gate/mlc_y10/placement/setTranslation 99.475 0 -20 mm
/gate/mlc_y10/placement/setRotationAxis 1 0 0
/gate/mlc_y10/placement/setRotationAngle 90 deg
/gate/mlc_y10/vis/setVisible 0
/gate/mlc_y10/vis/setColor magenta
/gate/mlc_leaf/daughters/name mlc_y11
/gate/mlc_leaf/daughters/insert wedge
/gate/mlc_y11/setMaterial Tungsten
/gate/mlc_y11/geometry/setNarrowerXLength 165.2 mm
/gate/mlc_y11/geometry/setXLength 164.3 mm
/gate/mlc_y11/geometry/setYLength 5 mm
/gate/mlc_y11/geometry/setZLength 3 mm
/gate/mlc_y11/placement/setTranslation 99.1 0 -25 mm
/gate/mlc_y11/placement/setRotationAxis 1 0 0
/gate/mlc_y11/placement/setRotationAngle 90 deg
/gate/mlc_y11/vis/setVisible 0
/gate/mlc_y11/vis/setColor magenta
/gate/mlc_leaf/daughters/name mlc_y12
/gate/mlc_leaf/daughters/insert wedge
/gate/mlc_y12/setMaterial Tungsten
/gate/mlc_y12/geometry/setNarrowerXLength 164.3 mm
/gate/mlc_y12/geometry/setXLength 163.1 mm
/gate/mlc_y12/geometry/setYLength 5 mm
/gate/mlc_y12/geometry/setZLength 3 mm
/gate/mlc_y12/placement/setTranslation 98.57499999999999 0 -30 mm
/gate/mlc_y12/placement/setRotationAxis 1 0 0
/gate/mlc_y12/placement/setRotationAngle 90 deg
/gate/mlc_y12/vis/setVisible 0
/gate/mlc_y12/vis/setColor magenta
/gate/mlc_leaf/daughters/name mlc_y13
/gate/mlc_leaf/daughters/insert wedge
/gate/mlc_y13/setMaterial Tungsten
/gate/mlc_y13/geometry/setNarrowerXLength 163.1 mm
/gate/mlc_y13/geometry/setXLength 162.0 mm
/gate/mlc_y13/geometry/setYLength 5 mm
/gate/mlc_y13/geometry/setZLength 3 mm
/gate/mlc_y13/placement/setTranslation 98.0 0 -35 mm
/gate/mlc_y13/placement/setRotationAxis 1 0 0
/gate/mlc_y13/placement/setRotationAngle 90 deg
/gate/mlc_y13/vis/setVisible 0
/gate/mlc_y13/vis/setColor magenta
/gate/mlc_leaf/daughters/name mlc_y14
/gate/mlc_leaf/daughters/insert wedge
/gate/mlc_y14/setMaterial Tungsten
/gate/mlc_y14/geometry/setNarrowerXLength 162.0 mm
/gate/mlc_y14/geometry/setXLength 160.5 mm
/gate/mlc_y14/geometry/setYLength 5 mm
/gate/mlc_y14/geometry/setZLength 3 mm
/gate/mlc_y14/placement/setTranslation 97.35 0 -40 mm
/gate/mlc_y14/placement/setRotationAxis 1 0 0
/gate/mlc_y14/placement/setRotationAngle 90 deg
/gate/mlc_y14/vis/setVisible 0
/gate/mlc_y14/vis/setColor magenta
/gate/mlc_y0/daughters/name mlc_y0_kill
/gate/mlc_y0/daughters/insert wedge
/gate/mlc_y0_kill/setMaterial Tungsten
/gate/mlc_y0_kill/geometry/setNarrowerXLength 153.5 mm
/gate/mlc_y0_kill/geometry/setXLength 154.5 mm
/gate/mlc_y0_kill/geometry/setYLength 5 mm
/gate/mlc_y0_kill/geometry/setZLength 3 mm
/gate/mlc_y0_kill/placement/setTranslation -5 0 0 mm
/gate/mlc_y0_kill/vis/setVisible 0
/gate/mlc_y0_kill/vis/setColor white
/gate/mlc_y1/daughters/name mlc_y1_kill
/gate/mlc_y1/daughters/insert wedge
/gate/mlc_y1_kill/setMaterial Tungsten
/gate/mlc_y1_kill/geometry/setNarrowerXLength 154.5 mm
/gate/mlc_y1_kill/geometry/setXLength 155.4 mm
/gate/mlc_y1_kill/geometry/setYLength 5 mm
/gate/mlc_y1_kill/geometry/setZLength 3 mm
/gate/mlc_y1_kill/placement/setTranslation -5 0 0 mm
/gate/mlc_y1_kill/vis/setVisible 0
/gate/mlc_y1_kill/vis/setColor white
/gate/mlc_y2/daughters/name mlc_y2_kill
/gate/mlc_y2/daughters/insert wedge
/gate/mlc_y2_kill/setMaterial Tungsten
/gate/mlc_y2_kill/geometry/setNarrowerXLength 155.4 mm
/gate/mlc_y2_kill/geometry/setXLength 156.1 mm
/gate/mlc_y2_kill/geometry/setYLength 5 mm
/gate/mlc_y2_kill/geometry/setZLength 3 mm
/gate/mlc_y2_kill/placement/setTranslation -5 0 0 mm
/gate/mlc_y2_kill/vis/setVisible 0
/gate/mlc_y2_kill/vis/setColor white
/gate/mlc_y3/daughters/name mlc_y3_kill
/gate/mlc_y3/daughters/insert wedge
/gate/mlc_y3_kill/setMaterial Tungsten
/gate/mlc_y3_kill/geometry/setNarrowerXLength 156.1 mm
/gate/mlc_y3_kill/geometry/setXLength 156.5 mm
/gate/mlc_y3_kill/geometry/setYLength 5 mm
/gate/mlc_y3_kill/geometry/setZLength 3 mm
/gate/mlc_y3_kill/placement/setTranslation -5 0 0 mm
/gate/mlc_y3_kill/vis/setVisible 0
/gate/mlc_y3_kill/vis/setColor white
/gate/mlc_y4/daughters/name mlc_y4_kill
/gate/mlc_y4/daughters/insert wedge
/gate/mlc_y4_kill/setMaterial Tungsten
/gate/mlc_y4_kill/geometry/setNarrowerXLength 156.5 mm
/gate/mlc_y4_kill/geometry/setXLength 156.9 mm
/gate/mlc_y4_kill/geometry/setYLength 5 mm
/gate/mlc_y4_kill/geometry/setZLength 3 mm
/gate/mlc_y4_kill/placement/setTranslation -5 0 0 mm
/gate/mlc_y4_kill/vis/setVisible 0
/gate/mlc_y4_kill/vis/setColor white
/gate/mlc_y5/daughters/name mlc_y5_kill
/gate/mlc_y5/daughters/insert wedge
/gate/mlc_y5_kill/setMaterial Tungsten
/gate/mlc_y5_kill/geometry/setNarrowerXLength 156.9 mm
/gate/mlc_y5_kill/geometry/setXLength 157.1 mm
/gate/mlc_y5_kill/geometry/setYLength 5 mm
/gate/mlc_y5_kill/geometry/setZLength 3 mm
/gate/mlc_y5_kill/placement/setTranslation -5 0 0 mm
/gate/mlc_y5_kill/vis/setVisible 0
/gate/mlc_y5_kill/vis/setColor white
/gate/mlc_y6/daughters/name mlc_y6_kill
/gate/mlc_y6/daughters/insert wedge
/gate/mlc_y6_kill/setMaterial Tungsten
/gate/mlc_y6_kill/geometry/setNarrowerXLength 157.1 mm
/gate/mlc_y6_kill/geometry/setXLength 156.9 mm
/gate/mlc_y6_kill/geometry/setYLength 5 mm
/gate/mlc_y6_kill/geometry/setZLength 3 mm
/gate/mlc_y6_kill/placement/setTranslation -5 0 0 mm
/gate/mlc_y6_kill/vis/setVisible 0
/gate/mlc_y6_kill/vis/setColor white
/gate/mlc_y7/daughters/name mlc_y7_kill
/gate/mlc_y7/daughters/insert wedge
/gate/mlc_y7_kill/setMaterial Tungsten
/gate/mlc_y7_kill/geometry/setNarrowerXLength 156.9 mm
/gate/mlc_y7_kill/geometry/setXLength 156.6 mm
/gate/mlc_y7_kill/geometry/setYLength 5 mm
/gate/mlc_y7_kill/geometry/setZLength 3 mm
/gate/mlc_y7_kill/placement/setTranslation -5 0 0 mm
/gate/mlc_y7_kill/vis/setVisible 0
/gate/mlc_y7_kill/vis/setColor white
/gate/mlc_y8/daughters/name mlc_y8_kill
/gate/mlc_y8/daughters/insert wedge
/gate/mlc_y8_kill/setMaterial Tungsten
/gate/mlc_y8_kill/geometry/setNarrowerXLength 156.6 mm
/gate/mlc_y8_kill/geometry/setXLength 156.2 mm
/gate/mlc_y8_kill/geometry/setYLength 5 mm
/gate/mlc_y8_kill/geometry/setZLength 3 mm
/gate/mlc_y8_kill/placement/setTranslation -5 0 0 mm
/gate/mlc_y8_kill/vis/setVisible 0
/gate/mlc_y8_kill/vis/setColor white
/gate/mlc_y9/daughters/name mlc_y9_kill
/gate/mlc_y9/daughters/insert wedge
/gate/mlc_y9_kill/setMaterial Tungsten
/gate/mlc_y9_kill/geometry/setNarrowerXLength 156.2 mm
/gate/mlc_y9_kill/geometry/setXLength 155.8 mm
/gate/mlc_y9_kill/geometry/setYLength 5 mm
/gate/mlc_y9_kill/geometry/setZLength 3 mm
/gate/mlc_y9_kill/placement/setTranslation -5 0 0 mm
/gate/mlc_y9_kill/vis/setVisible 0
/gate/mlc_y9_kill/vis/setColor white
/gate/mlc_y10/daughters/name mlc_y10_kill
/gate/mlc_y10/daughters/insert wedge
/gate/mlc_y10_kill/setMaterial Tungsten
/gate/mlc_y10_kill/geometry/setNarrowerXLength 155.8 mm
/gate/mlc_y10_kill/geometry/setXLength 155.2 mm
/gate/mlc_y10_kill/geometry/setYLength 5 mm
/gate/mlc_y10_kill/geometry/setZLength 3 mm
/gate/mlc_y10_kill/placement/setTranslation -5 0 0 mm
/gate/mlc_y10_kill/vis/setVisible 0
/gate/mlc_y10_kill/vis/setColor white
/gate/mlc_y11/daughters/name mlc_y11_kill
/gate/mlc_y11/daughters/insert wedge
/gate/mlc_y11_kill/setMaterial Tungsten
/gate/mlc_y11_kill/geometry/setNarrowerXLength 155.2 mm
/gate/mlc_y11_kill/geometry/setXLength 154.3 mm
/gate/mlc_y11_kill/geometry/setYLength 5 mm
/gate/mlc_y11_kill/geometry/setZLength 3 mm
/gate/mlc_y11_kill/placement/setTranslation -5 0 0 mm
/gate/mlc_y11_kill/vis/setVisible 0
/gate/mlc_y11_kill/vis/setColor white
/gate/mlc_y12/daughters/name mlc_y12_kill
/gate/mlc_y12/daughters/insert wedge
/gate/mlc_y12_kill/setMaterial Tungsten
/gate/mlc_y12_kill/geometry/setNarrowerXLength 154.3 mm
/gate/mlc_y12_kill/geometry/setXLength 153.1 mm
/gate/mlc_y12_kill/geometry/setYLength 5 mm
/gate/mlc_y12_kill/geometry/setZLength 3 mm
/gate/mlc_y12_kill/placement/setTranslation -5 0 0 mm
/gate/mlc_y12_kill/vis/setVisible 0
/gate/mlc_y12_kill/vis/setColor white
/gate/mlc_y13/daughters/name mlc_y13_kill
/gate/mlc_y13/daughters/insert wedge
/gate/mlc_y13_kill/setMaterial Tungsten
/gate/mlc_y13_kill/geometry/setNarrowerXLength 153.1 mm
/gate/mlc_y13_kill/geometry/setXLength 152.0 mm
/gate/mlc_y13_kill/geometry/setYLength 5 mm
/gate/mlc_y13_kill/geometry/setZLength 3 mm
/gate/mlc_y13_kill/placement/setTranslation -5 0 0 mm
/gate/mlc_y13_kill/vis/setVisible 0
/gate/mlc_y13_kill/vis/setColor white
/gate/actor/addActor KillActor KillInsides
# /gate/actor/KillInsides/save MyOutputFile1.txt
/gate/actor/KillInsides/attachTo mlc_leaf
/gate/actor/KillInsides/addFilter volumeFilter
/gate/actor/KillInsides/volumeFilter/addVolume mlc_y0_kill
/gate/actor/KillInsides/volumeFilter/addVolume mlc_y1_kill
/gate/actor/KillInsides/volumeFilter/addVolume mlc_y2_kill
/gate/actor/KillInsides/volumeFilter/addVolume mlc_y3_kill
/gate/actor/KillInsides/volumeFilter/addVolume mlc_y4_kill
/gate/actor/KillInsides/volumeFilter/addVolume mlc_y5_kill
/gate/actor/KillInsides/volumeFilter/addVolume mlc_y6_kill
/gate/actor/KillInsides/volumeFilter/addVolume mlc_y7_kill
/gate/actor/KillInsides/volumeFilter/addVolume mlc_y8_kill
/gate/actor/KillInsides/volumeFilter/addVolume mlc_y9_kill
/gate/actor/KillInsides/volumeFilter/addVolume mlc_y10_kill
/gate/actor/KillInsides/volumeFilter/addVolume mlc_y11_kill
/gate/actor/KillInsides/volumeFilter/addVolume mlc_y12_kill
/gate/actor/KillInsides/volumeFilter/addVolume mlc_y13_kill
/gate/mlc_leaf/repeaters/insert		genericRepeater
/gate/mlc_leaf/genericRepeater/setPlacementsFilename	leafedge.txt
/gate/mlc_leaf/genericRepeater/useRelativeTranslation	0
/gate/world/daughters/name jaws_y1Vol
/gate/world/daughters/insert box
/gate/jaws_y1Vol/setMaterial Air
/gate/jaws_y1Vol/geometry/setXLength 20 cm 	
/gate/jaws_y1Vol/geometry/setYLength 30 cm
/gate/jaws_y1Vol/geometry/setZLength 3 cm
/gate/jaws_y1Vol/placement/setTranslation -120.175 0.0 589 mm
/gate/jaws_y1Vol/vis/setVisible 0
/gate/jaws_y1Vol/vis/setColor red
/gate/jaws_y1Vol/daughters/name jaws_y1
/gate/jaws_y1Vol/daughters/insert wedge
/gate/jaws_y1/setMaterial Tungsten
/gate/jaws_y1/geometry/setNarrowerXLength 19.85 cm
/gate/jaws_y1/geometry/setXLength 20 cm 	
/gate/jaws_y1/geometry/setYLength 3 cm
/gate/jaws_y1/geometry/setZLength 30 cm
/gate/jaws_y1/vis/setVisible 0
/gate/jaws_y1/vis/setColor yellow
/gate/jaws_y1/placement/setTranslation 0 0 0 cm
/gate/jaws_y1/placement/setRotationAxis 1 0 0
/gate/jaws_y1/placement/setRotationAngle 270 deg
/gate/jaws_y1/daughters/name jaws_y1_kill
/gate/jaws_y1/daughters/insert wedge
/gate/jaws_y1_kill/setMaterial Tungsten
/gate/jaws_y1_kill/geometry/setNarrowerXLength 17.85 cm
/gate/jaws_y1_kill/geometry/setXLength 18 cm 	
/gate/jaws_y1_kill/geometry/setYLength 2.5 cm
/gate/jaws_y1_kill/geometry/setZLength 29 cm
/gate/jaws_y1_kill/vis/setVisible 0
/gate/jaws_y1_kill/vis/setColor white
/gate/jaws_y1_kill/placement/setTranslation 0 0 0 cm
/gate/world/daughters/name jaws_y2Vol
/gate/world/daughters/insert box
/gate/jaws_y2Vol/setMaterial Air
/gate/jaws_y2Vol/geometry/setXLength 20 cm 	
/gate/jaws_y2Vol/geometry/setYLength 3 cm
/gate/jaws_y2Vol/geometry/setZLength 30 cm
/gate/jaws_y2Vol/placement/setTranslation 120.175 0.0 589 mm
/gate/jaws_y2Vol/vis/setVisible 0
/gate/jaws_y2Vol/vis/setColor blue
/gate/jaws_y2Vol/placement/setRotationAxis 1 0 0
/gate/jaws_y2Vol/placement/setRotationAngle 90 deg
/gate/jaws_y2Vol/daughters/name jaws_y2
/gate/jaws_y2Vol/daughters/insert wedge
/gate/jaws_y2/setMaterial Tungsten
/gate/jaws_y2/geometry/setNarrowerXLength 19.85 cm
/gate/jaws_y2/geometry/setXLength 20 cm 	
/gate/jaws_y2/geometry/setYLength 3 cm
/gate/jaws_y2/geometry/setZLength 30 cm
/gate/jaws_y2/vis/setVisible 0
/gate/jaws_y2/vis/setColor yellow
/gate/jaws_y2/placement/setTranslation 0 0 0 cm
/gate/jaws_y2/placement/setRotationAxis 0 0 1
/gate/jaws_y2/placement/setRotationAngle 180 deg
/gate/jaws_y2/daughters/name jaws_y2_kill
/gate/jaws_y2/daughters/insert wedge
/gate/jaws_y2_kill/setMaterial Tungsten
/gate/jaws_y2_kill/geometry/setNarrowerXLength 17.85 cm
/gate/jaws_y2_kill/geometry/setXLength 18 cm 	
/gate/jaws_y2_kill/geometry/setYLength 2.5 cm
/gate/jaws_y2_kill/geometry/setZLength 29 cm
/gate/jaws_y2_kill/vis/setVisible 0
/gate/jaws_y2_kill/vis/setColor white
/gate/jaws_y2_kill/placement/setTranslation 0 0 0 cm
/gate/world/daughters/name jaws_x1Vol
/gate/world/daughters/insert box
/gate/jaws_x1Vol/setMaterial Air
/gate/jaws_x1Vol/geometry/setXLength 30 cm 	
/gate/jaws_x1Vol/geometry/setYLength 7.8 cm
/gate/jaws_x1Vol/geometry/setZLength 20 cm
/gate/jaws_x1Vol/placement/setTranslation 0 11.2525 53 cm
/gate/jaws_x1Vol/vis/setVisible 0
/gate/jaws_x1Vol/vis/setColor magenta
/gate/jaws_x1Vol/placement/setRotationAxis 1 0 0
/gate/jaws_x1Vol/placement/setRotationAngle 270 deg
/gate/jaws_x1Vol/daughters/name jaws_x1
/gate/jaws_x1Vol/daughters/insert wedge
/gate/jaws_x1/setMaterial Tungsten
/gate/jaws_x1/geometry/setNarrowerXLength 17.61 cm 	
/gate/jaws_x1/geometry/setXLength 18 cm 	
/gate/jaws_x1/geometry/setYLength 78 mm
/gate/jaws_x1/geometry/setZLength 30 cm
/gate/jaws_x1/placement/setTranslation 0 0 0 cm
/gate/jaws_x1/vis/setVisible 0
/gate/jaws_x1/vis/setColor cyan
/gate/jaws_x1/placement/setRotationAxis 0 1 0
/gate/jaws_x1/placement/setRotationAngle 90 deg
/gate/jaws_x1/daughters/name jaws_x1_kill
/gate/jaws_x1/daughters/insert wedge
/gate/jaws_x1_kill/setMaterial Tungsten
/gate/jaws_x1_kill/geometry/setNarrowerXLength 15.61 cm 	
/gate/jaws_x1_kill/geometry/setXLength 16 cm 	
/gate/jaws_x1_kill/geometry/setYLength 1 mm
/gate/jaws_x1_kill/geometry/setZLength 29 cm
/gate/jaws_x1_kill/placement/setTranslation 0 -3.7 0 cm
/gate/jaws_x1_kill/vis/setVisible 0
/gate/jaws_x1_kill/vis/setColor white
/gate/world/daughters/name jaws_x2Vol
/gate/world/daughters/insert box
/gate/jaws_x2Vol/setMaterial Air
/gate/jaws_x2Vol/geometry/setXLength 30 cm 	
/gate/jaws_x2Vol/geometry/setYLength 7.8 cm
/gate/jaws_x2Vol/geometry/setZLength 20 cm
/gate/jaws_x2Vol/placement/setTranslation 0 -11.2525 53 cm
/gate/jaws_x2Vol/vis/setVisible 0
/gate/jaws_x2Vol/vis/setColor magenta
/gate/jaws_x2Vol/placement/setRotationAxis 1 0 0
/gate/jaws_x2Vol/placement/setRotationAngle 270 deg
/gate/jaws_x2Vol/daughters/name jaws_x2
/gate/jaws_x2Vol/daughters/insert wedge
/gate/jaws_x2/setMaterial Tungsten
/gate/jaws_x2/geometry/setNarrowerXLength 17.61 cm 	
/gate/jaws_x2/geometry/setXLength 18 cm 	
/gate/jaws_x2/geometry/setYLength 78 mm
/gate/jaws_x2/geometry/setZLength 30 cm
/gate/jaws_x2/placement/setTranslation 0 0 0 cm
/gate/jaws_x2/vis/setVisible 0
/gate/jaws_x2/vis/setColor cyan
/gate/jaws_x2/placement/setRotationAxis 0 1 0
/gate/jaws_x2/placement/setRotationAngle 270 deg
/gate/jaws_x2/daughters/name jaws_x2_kill
/gate/jaws_x2/daughters/insert wedge
/gate/jaws_x2_kill/setMaterial Tungsten
/gate/jaws_x2_kill/geometry/setNarrowerXLength 15.61 cm 	
/gate/jaws_x2_kill/geometry/setXLength 16 cm 	
/gate/jaws_x2_kill/geometry/setYLength 1 mm
/gate/jaws_x2_kill/geometry/setZLength 29 cm
/gate/jaws_x2_kill/placement/setTranslation 0 -3.7 0 cm
/gate/jaws_x2_kill/vis/setVisible 0
/gate/jaws_x2_kill/vis/setColor white
/gate/actor/addActor KillActor KillInsides2
# /gate/actor/KillInsides2/save MyOutputFile21.txt
/gate/actor/KillInsides2/attachTo jaws_y1Vol
/gate/actor/KillInsides2/addFilter volumeFilter
/gate/actor/KillInsides2/volumeFilter/addVolume jaws_y1_kill
/gate/actor/addActor KillActor KillInsides4
# /gate/actor/KillInsides4/save MyOutputFile41.txt
/gate/actor/KillInsides4/attachTo jaws_y2Vol
/gate/actor/KillInsides4/addFilter volumeFilter
/gate/actor/KillInsides4/volumeFilter/addVolume jaws_y2_kill
/gate/actor/addActor KillActor KillInsides3
# /gate/actor/KillInsides3/save MyOutputFile31.txt
/gate/actor/KillInsides3/attachTo jaws_x1Vol
/gate/actor/KillInsides3/addFilter volumeFilter
/gate/actor/KillInsides3/volumeFilter/addVolume jaws_x1_kill
/gate/actor/addActor KillActor KillInsides5
# /gate/actor/KillInsides5/save MyOutputFile51.txt
/gate/actor/KillInsides5/attachTo jaws_x2Vol
/gate/actor/KillInsides5/addFilter volumeFilter
/gate/actor/KillInsides5/volumeFilter/addVolume jaws_x2_kill

/gate/world/daughters/name PhS_Plane_Two
/gate/world/daughters/insert box
/gate/PhS_Plane_Two/setMaterial Vacuum
/gate/PhS_Plane_Two/geometry/setXLength 15 cm
/gate/PhS_Plane_Two/geometry/setYLength 15 cm
/gate/PhS_Plane_Two/geometry/setZLength 1 nm
/gate/PhS_Plane_Two/placement/setTranslation 0.0 0.0 471 mm
/gate/PhS_Plane_Two/vis/setColor cyan
/gate/PhS_Plane_Two/vis/setVisible 0
/gate/world/daughters/name FS_Plane
/gate/world/daughters/insert box
/gate/FS_Plane/setMaterial Air	
/gate/FS_Plane/geometry/setXLength 40 cm
/gate/FS_Plane/geometry/setYLength 40 cm
/gate/FS_Plane/geometry/setZLength 1 nm
/gate/FS_Plane/placement/setTranslation 0.0 0.0 0.0 mm
/gate/FS_Plane/vis/setColor cyan
/gate/FS_Plane/vis/setVisible 0
/gate/world/daughters/name Kill_BackPlane
/gate/world/daughters/insert box
/gate/Kill_BackPlane/setMaterial Air	
/gate/Kill_BackPlane/geometry/setXLength 80 cm
/gate/Kill_BackPlane/geometry/setYLength 80 cm
/gate/Kill_BackPlane/geometry/setZLength 1 nm
/gate/Kill_BackPlane/placement/setTranslation 0.0 0.0 730 mm
/gate/Kill_BackPlane/vis/setColor red
/gate/Kill_BackPlane/vis/setVisible 0
/gate/world/daughters/name Kill_FrontPlane
/gate/world/daughters/insert box
/gate/Kill_FrontPlane/setMaterial Air	
/gate/Kill_FrontPlane/geometry/setXLength 80 cm
/gate/Kill_FrontPlane/geometry/setYLength 80 cm
/gate/Kill_FrontPlane/geometry/setZLength 1 nm
/gate/Kill_FrontPlane/placement/setTranslation 0.0 0.0 -10 mm
/gate/Kill_FrontPlane/vis/setColor red
/gate/Kill_FrontPlane/vis/setVisible 0
/gate/physics/addPhysicsList emstandard_opt3
/gate/physics/Gamma/SetCutInRegion world 1 mm
/gate/physics/Electron/SetCutInRegion world 1 mm
/gate/physics/Positron/SetCutInRegion world 1 mm
/gate/physics/Gamma/SetCutInRegion mlc_leaf 0.001 mm
/gate/physics/Electron/SetCutInRegion mlc_leaf 0.001 mm
/gate/physics/Positron/SetCutInRegion mlc_leaf 0.001 mm
/gate/physics/Gamma/SetCutInRegion jaws_y1 0.001 mm
/gate/physics/Electron/SetCutInRegion jaws_y1 0.001 mm
/gate/physics/Positron/SetCutInRegion jaws_y1 0.001 mm
/gate/physics/Gamma/SetCutInRegion jaws_y2 0.001 mm
/gate/physics/Electron/SetCutInRegion jaws_y2 0.001 mm
/gate/physics/Positron/SetCutInRegion jaws_y2 0.001 mm
/gate/physics/Gamma/SetCutInRegion jaws_x1 0.001 mm
/gate/physics/Electron/SetCutInRegion jaws_x1 0.001 mm
/gate/physics/Positron/SetCutInRegion jaws_x1 0.001 mm
/gate/physics/Gamma/SetCutInRegion jaws_x2 0.001 mm
/gate/physics/Electron/SetCutInRegion jaws_x2 0.001 mm
/gate/physics/Positron/SetCutInRegion jaws_x2 0.001 mm
/gate/physics/addProcess Compton
/gate/physics/processes/Compton/setModel StandardModel gamma
/gate/physics/processes/Compton/activateSplitting gamma 50
/gate/actor/addActor PhaseSpaceActor PhS_g
/gate/actor/PhS_g/attachTo PhS_Plane_Two
/gate/actor/PhS_g/save 	 output-lana2-PhS-g935.root
/gate/actor/PhS_g/enableParticleName false
/gate/actor/PhS_g/enableProductionVolume true
/gate/actor/PhS_g/enableProductionProcess true
/gate/actor/PhS_g/useVolumeFrame true
/gate/actor/PhS_g/addFilter particleFilter
/gate/actor/PhS_g/particleFilter/addParticle gamma
/gate/actor/PhS_g/enableZPosition true
/gate/actor/addActor PhaseSpaceActor PhS_e
/gate/actor/PhS_e/attachTo PhS_Plane_Two
/gate/actor/PhS_e/save 	 output-lana2-PhS-e935.root
/gate/actor/PhS_e/enableParticleName false
/gate/actor/PhS_e/enableProductionVolume true
/gate/actor/PhS_e/enableProductionProcess true
/gate/actor/PhS_e/useVolumeFrame true
/gate/actor/PhS_e/addFilter particleFilter
/gate/actor/PhS_e/particleFilter/addParticle e-
/gate/actor/PhS_e/particleFilter/addParticle e+
/gate/actor/PhS_e/enableZPosition true
/gate/actor/addActor PhaseSpaceActor FieldSizeChecker
/gate/actor/FieldSizeChecker/attachTo FS_Plane
/gate/actor/FieldSizeChecker/save 	 FieldSizeChecker935.root
/gate/actor/FieldSizeChecker/enableParticleName false
/gate/actor/FieldSizeChecker/enableProductionVolume true
/gate/actor/FieldSizeChecker/enableProductionProcess true
/gate/actor/FieldSizeChecker/useVolumeFrame true
/gate/actor/FieldSizeChecker/addFilter particleFilter
/gate/actor/FieldSizeChecker/particleFilter/addParticle gamma
/gate/actor/FieldSizeChecker/enableZPosition true
/gate/actor/addActor KillActor Kill_BP
/gate/actor/Kill_BP/attachTo Kill_BackPlane
/gate/actor/addActor KillActor Kill_FP
/gate/actor/Kill_FP/attachTo Kill_FrontPlane
/gate/run/initialize
/gate/source/addSource beam_g phaseSpace
/gate/source/beam_g/addPhaseSpaceFile /hdfs/user/lb8075/ClusterAllOne_main_phs1_HighStat/Renum/output-lana-PhS1-g935.root
/gate/source/beam_g/setParticleType gamma
/gate/source/beam_g/attachTo PhS_Plane
/gate/source/beam_g/useRandomSymmetry true
/gate/random/setEngineName MersenneTwister

/gate/application/noGlobalOutput

/gate/application/setTotalNumberOfPrimaries 1000000
/gate/random/setEngineSeed 1363166736874990365
/gate/application/setTimeStart 0. s
/gate/application/addSlice     1. s
/gate/application/startDAQCluster 0 1 0 s

/gate/physics/processList Enabled
/gate/physics/processList Initialized
