#!/bin/bash 
#PBS -l walltime=22:59:59
#PBS -j oe
#PBS -l select=1:ncpus=1
#PBS -l select=1:ncpus=1:mem=500mb
#PBS -J 1,4,8,10,17,18,25,28,31,34,41,47,48,50,55,56,69,73,76,80,85,86,88,97,99,103,107,112,113,115,116,117,118,124,126,127,128,129,130,132,134,136,137,138,142,144,145,153,154,155,156,158,161,165,169,170,173,175,176,181,183,184,185,186,187,188,190,191,195,197,198
#PBS -o /work/lb8075/job_logfiles

module add apps/gate/8.2
myScript="Main_PhS3_BigSensor_Flexible_airbox_wCopper.mac"
cat /home/lb8075/linac/mac/Main_PhS3_BigSensor_Flexible_airbox_wCopper.mac
now=$(date)
echo "Start: $now"
prim=1010000 #for elec

myCommand="cp /home/lb8075/linac/mac/Main_PhS3_BigSensor_Flexible_airbox_wCopper.mac .; Gate $myScript -a '[seed,$RANDOM$RANDOM$RANDOM] [primaries,$prim] [pathGateMaterials,/home/lb8075/linac/data/GateMaterials.db] [id,$PBS_ARRAY_INDEX] [pathOutputDose,/work/lb8075/PhaseSpaces/PS3/PhS3BigSensor_v6_ElectronsFromPhS1_10x10] [inputParticleType,/gate/source/beam_g/setParticleType e-] [inputPhaseSpaceFile,/work/lb8075/PhaseSpaces/GenPhS2/Generated_PhS2_ElectronsFromPhS1_10x10/generatedElectron_PhS2_v4_10x10] [grating_material,Aluminium] [foil_thick_um,50] [foil_z_um,469975.0] [pass_z_um,469946.5] [epi_z_um,469940.5] [bulk_z_um,469588.0]'" 
eval $myCommand
echo "Completion time is $(date)" 

