#!/bin/bash 
#PBS -l walltime=22:59:59
#PBS -j oe
#PBS -l select=1:ncpus=1
#PBS -l select=1:ncpus=1:mem=500mb
#PBS -J 2,6,7,9,10,13,14,18,20,21,23,24,25,31,32,33,35,48,51,55,60,62,76,77,82,86,88,93,94,97,98,103,104,108,115,118,122,125,127,129,131,133,134,135,137,138,159,168,173,176,186,187,191,192,193,194,195,199,200
#PBS -o /work/lb8075/job_logfiles

module add apps/gate/8.2
myScript="Main_PhS3_BigSensor_Flexible_airbox_wCopper.mac"
cat /home/lb8075/linac/mac/Main_PhS3_BigSensor_Flexible_airbox_wCopper.mac
now=$(date)
echo "Start: $now"
prim=18978380 #for elec

myCommand="cp /home/lb8075/linac/mac/Main_PhS3_BigSensor_Flexible_airbox_wCopper.mac .; Gate $myScript -a '[seed,$RANDOM$RANDOM$RANDOM] [primaries,$prim] [pathGateMaterials,/home/lb8075/linac/data/GateMaterials.db] [id,$PBS_ARRAY_INDEX] [pathOutputDose,/work/lb8075/PhaseSpaces/PS3/PhS3BigSensor_v6_ElectronsFromPhS1_highEn_40x40] [inputParticleType,/gate/source/beam_g/setParticleType e-] [inputPhaseSpaceFile,/work/lb8075/PhaseSpaces/GenPhS2/Generated_PhS2_ElectronsFromPhS1_highEn_40x40/generatedElectron_PhS2_v4_40x40] [grating_material,Copper] [foil_thick_um,4] [foil_z_um,469998.0] [pass_z_um,469992.5] [epi_z_um,469986.5] [bulk_z_um,469634.0]'" 
eval $myCommand
echo "Completion time is $(date)" 

