#!/bin/bash 
#PBS -l walltime=22:59:59
#PBS -j oe
#PBS -l select=1:ncpus=1
#PBS -l select=1:ncpus=1:mem=500mb
#PBS -J 1,2,6,10,11,22,28,29,52,69,76,79,84,91,139,142,150,151,161,162,163,171,182,185,199
#PBS -o /work/lb8075/job_logfiles

module add apps/gate/8.2
myScript="Main_PhS3_BigSensor_Flexible_airbox_wCopper.mac"
cat /home/lb8075/linac/mac/Main_PhS3_BigSensor_Flexible_airbox_wCopper.mac
now=$(date)
echo "Start: $now"
prim=1010000 #for elec

myCommand="cp /home/lb8075/linac/mac/Main_PhS3_BigSensor_Flexible_airbox_wCopper.mac .; Gate $myScript -a '[seed,$RANDOM$RANDOM$RANDOM] [primaries,$prim] [pathGateMaterials,/home/lb8075/linac/data/GateMaterials.db] [id,$PBS_ARRAY_INDEX] [pathOutputDose,/work/lb8075/PhaseSpaces/PS3/PhS3BigSensor_v6_ElectronsFromPhS1_10x10] [inputParticleType,/gate/source/beam_g/setParticleType e-] [inputPhaseSpaceFile,/work/lb8075/PhaseSpaces/GenPhS2/Generated_PhS2_ElectronsFromPhS1_10x10/generatedElectron_PhS2_v4_10x10] [grating_material,Aluminium] [foil_thick_um,200] [foil_z_um,469900.0] [pass_z_um,469796.5] [epi_z_um,469790.5] [bulk_z_um,469438.0]'" 
eval $myCommand
echo "Completion time is $(date)" 

