#!/bin/bash 
#PBS -l walltime=22:59:59
#PBS -j oe
#PBS -l select=1:ncpus=1
#PBS -l select=1:ncpus=1:mem=500mb
#PBS -J 4,5,6,10,12,16,18,19,20,21,22,25,26,27,28,29,30,32,33,34,35,39,40,41,42,43,46,48,50,60,62,63,66,67,70,71,72,73,74,75,78,81,88,89,91,96,97,101,102,104,106,110,130,132,134,139,147,148
#PBS -o /work/lb8075/job_logfiles

module add apps/gate/8.2
myScript="Main_PhS3_BigSensor_Flexible_airbox_wCopper.mac"
cat /home/lb8075/linac/mac/Main_PhS3_BigSensor_Flexible_airbox_wCopper.mac
now=$(date)
echo "Start: $now"
prim=18978380 #for elec

myCommand="cp /home/lb8075/linac/mac/Main_PhS3_BigSensor_Flexible_airbox_wCopper.mac .; Gate $myScript -a '[seed,$RANDOM$RANDOM$RANDOM] [primaries,$prim] [pathGateMaterials,/home/lb8075/linac/data/GateMaterials.db] [id,$PBS_ARRAY_INDEX] [pathOutputDose,/work/lb8075/PhaseSpaces/PS3/PhS3BigSensor_v6_ElectronsFromPhS1_highEn_40x40] [inputParticleType,/gate/source/beam_g/setParticleType e-] [inputPhaseSpaceFile,/work/lb8075/PhaseSpaces/GenPhS2/Generated_PhS2_ElectronsFromPhS1_highEn_40x40/generatedElectron_PhS2_v4_40x40] [grating_material,Copper] [foil_thick_um,8] [foil_z_um,469996.0] [pass_z_um,469988.5] [epi_z_um,469982.5] [bulk_z_um,469630.0]'" 
eval $myCommand
echo "Completion time is $(date)" 

