#!/bin/bash 
#PBS -l walltime=11:59:00
#PBS -j oe
#PBS -l select=1:ncpus=1
#PBS -l select=1:ncpus=1:mem=500mb
#PBS -J 1-200
#PBS -o /work/lb8075/job_logfiles

module add apps/gate/8.2
myScript="/home/lb8075/linac/mac/Main_PhS3_BigSensor_Flexible_airbox_wCopper.mac"
cat $myScript
now=$(date)
echo "Start: $now"
prim=19901450 #for elec

myCommand="Gate $myScript -a '[seed,$RANDOM$RANDOM$RANDOM] [primaries,$prim] [pathGateMaterials,/home/lb8075/linac/data/GateMaterials.db] [id,$PBS_ARRAY_INDEX] [pathOutputDose,/work/lb8075/PhaseSpaces/PS3/PhS3BigSensor_v4_ElectronsFromPhS1_40x40] [inputParticleType,/gate/source/beam_g/setParticleType e-] [inputPhaseSpaceFile,/work/lb8075/PhaseSpaces/GenPhS2/Generated_PhS2_ElectronsFromPhS1_40x40/generatedElectron_PhS2_v4_40x40] [grating_material,Copper] [foil_thick_um,4] [foil_z_um,469998.0] [pass_z_um,469991.0] [epi_z_um,469981.0] [bulk_z_um,469626.0]'" 
eval $myCommand
echo "Completion time is $(date)" 

