#!/bin/bash 
#PBS -l walltime=11:59:00
#PBS -j oe
#PBS -l select=1:ncpus=1
#PBS -l select=1:ncpus=1:mem=500mb
#PBS -J 1-200
#PBS -o /work/lb8075/job_logfiles

module add apps/gate/8.2
myScript="/home/lb8075/linac/mac/Main_PhS3_BigSensor_Flexible_airbox_wCopper.mac"
cat $myScript
now=$(date)
echo "Start: $now"
prim=12233680 #for elec

myCommand="Gate $myScript -a '[seed,$RANDOM$RANDOM$RANDOM] [primaries,$prim] [pathGateMaterials,/home/lb8075/linac/data/GateMaterials.db] [id,$PBS_ARRAY_INDEX] [pathOutputDose,/work/lb8075/PhaseSpaces/PS3/PhS3BigSensor_v4_ElectronsFromPhS1_30x30] [inputParticleType,/gate/source/beam_g/setParticleType e-] [inputPhaseSpaceFile,/work/lb8075/PhaseSpaces/GenPhS2/Generated_PhS2_ElectronsFromPhS1_30x30/generatedElectron_PhS2_v4_30x30] [grating_material,Aluminium] [foil_thick_um,350] [foil_z_um,469825.0] [pass_z_um,469645.0] [epi_z_um,469635.0] [bulk_z_um,469280.0]'" 
eval $myCommand
echo "Completion time is $(date)" 

