#!/bin/bash 
#PBS -l walltime=22:59:59
#PBS -j oe
#PBS -l select=1:ncpus=1
#PBS -l select=1:ncpus=1:mem=500mb
#PBS -J 1-200 
#PBS -o /work/lb8075/job_logfiles

module add apps/gate/8.2
myScript="Main_PhS3_BigSensor_Flexible_airbox_noCopper.mac"
cat /home/lb8075/linac/mac/Main_PhS3_BigSensor_Flexible_airbox_noCopper.mac
now=$(date)
echo "Start: $now"
prim=12697550 #for elec

myCommand="cp /home/lb8075/linac/mac/Main_PhS3_BigSensor_Flexible_airbox_noCopper.mac .; Gate $myScript -a '[seed,$RANDOM$RANDOM$RANDOM] [primaries,$prim] [pathGateMaterials,/home/lb8075/linac/data/GateMaterials.db] [id,$PBS_ARRAY_INDEX] [pathOutputDose,/work/lb8075/PhaseSpaces/PS3/PhS3BigSensor_v6_Electrons_highEn_40x40] [inputParticleType,/gate/source/beam_g/setParticleType e-] [inputPhaseSpaceFile,/work/lb8075/PhaseSpaces/GenPhS2/Generated_PhS2_Electrons_highEn_40x40/generatedElectron_PhS2_v4_40x40] [grating_material,Aluminium] [pass_z_um,469996.5] [epi_z_um,469990.5] [bulk_z_um,469638.0]'" 
eval $myCommand
echo "Completion time is $(date)" 

