#!/bin/bash 
#PBS -l walltime=22:59:59
#PBS -j oe
#PBS -l select=1:ncpus=1
#PBS -l select=1:ncpus=1:mem=500mb
#PBS -J 16,23,24,56,74,78,79,89,91,93,95,105,115,120,126,131,134,142,146,148,155,159,184,187,200
#PBS -o /work/lb8075/job_logfiles

module add apps/gate/8.2
myScript="Main_PhS3_BigSensor_Flexible_airbox_wCopper.mac"
cat /home/lb8075/linac/mac/Main_PhS3_BigSensor_Flexible_airbox_wCopper.mac
now=$(date)
echo "Start: $now"
prim=18978380 #for elec

myCommand="cp /home/lb8075/linac/mac/Main_PhS3_BigSensor_Flexible_airbox_wCopper.mac .; Gate $myScript -a '[seed,$RANDOM$RANDOM$RANDOM] [primaries,$prim] [pathGateMaterials,/home/lb8075/linac/data/GateMaterials.db] [id,$PBS_ARRAY_INDEX] [pathOutputDose,/work/lb8075/PhaseSpaces/PS3/PhS3BigSensor_v6_ElectronsFromPhS1_highEn_40x40] [inputParticleType,/gate/source/beam_g/setParticleType e-] [inputPhaseSpaceFile,/work/lb8075/PhaseSpaces/GenPhS2/Generated_PhS2_ElectronsFromPhS1_highEn_40x40/generatedElectron_PhS2_v4_40x40] [grating_material,Copper] [foil_thick_um,16] [foil_z_um,469992.0] [pass_z_um,469980.5] [epi_z_um,469974.5] [bulk_z_um,469622.0]'" 
eval $myCommand
echo "Completion time is $(date)" 

