
#=====================================================
# VERBOSITY
#=====================================================

/control/execute mac/verbose.mac

#=====================================================
# VISUALISATION
#=====================================================

/control/execute mac/visu.mac

# =====================================================
# GEOMETRY
# =====================================================

/gate/geometry/setMaterialDatabase data/GateMaterials.db

# WORLD
/gate/world/setMaterial            Air
/gate/world/geometry/setXLength    1 m
/gate/world/geometry/setYLength    1 m
/gate/world/geometry/setZLength    2.5 m
# /gate/world/vis/setVisible 1

# LINAC HEAD
# World origin is in the center of the beam e- source (not the real
# isocenter of the gantry room)
/gate/geometry/setMaterialDatabase data/LinacMaterials.db
/control/execute mac/linac_head_1B.mac


# VIRTUAL PLANE FOR PHASE SPACE
/gate/linac/daughters/name               PhS_Plane_b4FF
/gate/linac/daughters/insert             cylinder
/gate/PhS_Plane_b4FF/setMaterial              Air
/gate/PhS_Plane_b4FF/geometry/setRmin         0 mm
/gate/PhS_Plane_b4FF/geometry/setRmax         35 mm
/gate/PhS_Plane_b4FF/geometry/setHeight       1 nm
/gate/PhS_Plane_b4FF/placement/setTranslation 0.0 0.0 -121 mm
/gate/PhS_Plane_b4FF/vis/setColor             yellow
/gate/PhS_Plane_b4FF/vis/setVisible           1
# VIRTUAL PLANE FOR PHASE SPACE
/gate/linac/daughters/name               PhS_Plane
/gate/linac/daughters/insert             cylinder
/gate/PhS_Plane/setMaterial              Vacuum
/gate/PhS_Plane/geometry/setRmin         0 mm
/gate/PhS_Plane/geometry/setRmax         85 mm
/gate/PhS_Plane/geometry/setHeight       1 nm
/gate/PhS_Plane/placement/setTranslation 0.0 0.0 -297 mm
/gate/PhS_Plane/vis/setColor             white
/gate/PhS_Plane/vis/setVisible           1

# -----------------------------------------------------
# Jaws
# -----------------------------------------------------

# /control/execute mac/linac_jaws.mac

# =====================================================
# PHYSICS
# =====================================================

/gate/physics/addPhysicsList emstandard_opt3

/gate/physics/Gamma/SetCutInRegion      world 1 mm
/gate/physics/Electron/SetCutInRegion   world 1 mm
/gate/physics/Positron/SetCutInRegion   world 1 mm

/gate/physics/Gamma/SetCutInRegion      ionizing_chamber 0.5 mm
/gate/physics/Electron/SetCutInRegion   ionizing_chamber 0.5 mm
/gate/physics/Positron/SetCutInRegion   ionizing_chamber 0.5 mm

/gate/physics/Gamma/SetCutInRegion      back_scatter_plate 0.5 mm
/gate/physics/Electron/SetCutInRegion   back_scatter_plate 0.5 mm
/gate/physics/Positron/SetCutInRegion   back_scatter_plate 0.5 mm

/gate/physics/Gamma/SetCutInRegion      mirror 0.5 mm
/gate/physics/Electron/SetCutInRegion   mirror 0.5 mm
/gate/physics/Positron/SetCutInRegion   mirror 0.5 mm

/gate/physics/Gamma/SetCutInRegion      flattening_filter_cone6 0.5 mm
/gate/physics/Electron/SetCutInRegion   flattening_filter_cone6 0.5 mm
/gate/physics/Positron/SetCutInRegion   flattening_filter_cone6 0.5 mm

# /gate/physics/addProcess Bremsstrahlung
# /gate/physics/processes/Bremsstrahlung/setModel StandardModel e-
# /gate/physics/processes/Bremsstrahlung/setModel StandardModel e+
# /gate/physics/processes/Bremsstrahlung/activateSplitting e- 20
# /gate/physics/processes/Bremsstrahlung/addFilter volumeFilter secondaries
# /gate/physics/processes/Bremsstrahlung/secondaries/volumeFilter/addVolume target

# /gate/physics/addProcess Compton
# /gate/physics/processes/Compton/setModel StandardModel gamma
# /gate/physics/processes/Compton/activateSplitting gamma 100
# /gate/physics/processes/Compton/addFilter volumeFilter secondaries
# /gate/physics/processes/Compton/secondaries/volumeFilter/addVolume flattening_filter


/gate/physics/processList Enabled
/gate/physics/processList Initialized
# /gate/physics/print PhysicsCuts.txt
#=====================================================
# DETECTORS
#=====================================================

# ----------------------------------------------------
# Kill actor to stop particles when they go inside a region

/gate/actor/addActor          KillActor killer0
/gate/actor/killer0/attachTo  kill_box_top
/gate/actor/addActor          KillActor killer1
/gate/actor/killer1/attachTo  kill_box_bottom
/gate/actor/addActor          KillActor killer2
/gate/actor/killer2/attachTo  kill_box_bottom2

# ----------------------------------------------------
# the following actor regularly store the current number of
# event/track/step in a file

/gate/actor/addActor               SimulationStatisticActor stat
/gate/actor/stat/save              output/output-writePhS-stat.txt
/gate/actor/stat/saveEveryNSeconds 20

# ----------------------------------------------------
# Phase space storage (a PhS for gamma, another for e-)

/gate/actor/addActor                         PhaseSpaceActor PhS_g
/gate/actor/PhS_g/attachTo                   PhS_Plane
/gate/actor/PhS_g/save 	                     output/output-PhS-g.root
/gate/actor/PhS_g/enableParticleName         false
/gate/actor/PhS_g/enableProductionVolume     false
/gate/actor/PhS_g/enableProductionProcess    false
/gate/actor/PhS_g/useVolumeFrame             true
/gate/actor/PhS_g/addFilter                  particleFilter
/gate/actor/PhS_g/particleFilter/addParticle gamma
/gate/actor/PhS_g/enableZPosition            true
#/gate/actor/PhS_g/saveEveryNSeconds          20

/gate/actor/addActor                         PhaseSpaceActor PhS_e
/gate/actor/PhS_e/attachTo                   PhS_Plane
/gate/actor/PhS_e/save 	                     output/output-PhS-e.root
/gate/actor/PhS_e/enableParticleName         false
/gate/actor/PhS_e/enableProductionVolume     false
/gate/actor/PhS_e/enableProductionProcess    false
/gate/actor/PhS_e/useVolumeFrame             true
/gate/actor/PhS_e/addFilter                  particleFilter
/gate/actor/PhS_e/particleFilter/addParticle e-
/gate/actor/PhS_e/particleFilter/addParticle e+
/gate/actor/PhS_e/enableZPosition            true
# /gate/actor/PhS_e/saveEveryNSeconds          20

#=====================================================
# INITIALISATION
#=====================================================


/gate/run/initialize
# Bremsstrahlung splitting : generate 100 photon (if below 100 MeV) with weight 1/100

/process/em/setBiasingFactor compt 100 True
/process/em/setSecBiasing compt flattening_filter_cone6 100 100 MeV

#====================================================
# BEAMS
#=====================================================

/gate/source/addSource                         beam_g phaseSpace
/gate/source/beam_g/addPhaseSpaceFile          output/output-phs1A-gb2_Biasx100.root
# /gate/source/beam_g/setParticleType            gamma
/gate/source/beam_g/attachTo                   PhS_Plane_b4FF
/gate/source/beam_g/useRandomSymmetry          true


#=====================================================
# START BEAMS
#=====================================================

/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed auto
/gate/application/noGlobalOutput

#/tracking/verbose 2

/gate/application/setTotalNumberOfPrimaries 2000
/gate/application/start


/gate/physics/processList Enabled
/gate/physics/processList Initialized
