
# INPUTS
# pathGateMaterials
# pathOutputDose
# id
# inputPhaseSpaceFile
# seed 
# primaries
# [inputPhaseSpaceFile,/Users/lb8075/gate-exercices-master-linac/linac/generatedGammasnSkimmed10Halfmm1.root] [seed,12345678] [primaries,200] [pathGateMaterials,/Users/lb8075/gate-exercices-master-linac/linac/data/GateMaterials.db] [id,1] [pathOutputDose,/Users/lb8075/gate-exercices-master-linac/linac/output/BigSensorTest.root]
# [inputPhaseSpaceFile,/work/lb8075/PhaseSpaces/Generated_PhS2_Electrons_40x40/generatedElectron_PhS2_v4_40x40_199_] [seed,12345678] [primaries,200] [pathGateMaterials,data/GateMaterials.db] [id,1] [pathOutputDose,BigSensorTest.root]
#
#=====================================================
# VISUALISATION
#=====================================================

# /control/execute mac/visu.mac

# =====================================================
# GEOMETRY
# =====================================================

/gate/geometry/setMaterialDatabase {pathGateMaterials}
#/home/lb8075/linac/data/GateMaterials.db

# WORLD
/gate/world/setMaterial            Air
/gate/world/geometry/setXLength    0.3 m
/gate/world/geometry/setYLength    0.3 m
/gate/world/geometry/setZLength    1 m
/gate/world/vis/setVisible 1


/gate/world/daughters/name                   PhS_Plane_Two
/gate/world/daughters/insert                 box
/gate/PhS_Plane_Two/setMaterial              Vacuum
/gate/PhS_Plane_Two/geometry/setXLength      25 cm
/gate/PhS_Plane_Two/geometry/setYLength      25 cm
/gate/PhS_Plane_Two/geometry/setZLength      1 nm
/gate/PhS_Plane_Two/placement/setTranslation 0.0 0.0 471 mm #(-529)
/gate/PhS_Plane_Two/vis/setColor             cyan
/gate/PhS_Plane_Two/vis/setVisible           1


/gate/world/daughters/name                   Kill_BackPlane
/gate/world/daughters/insert                 box
/gate/Kill_BackPlane/setMaterial                   Air	
/gate/Kill_BackPlane/geometry/setXLength           30 cm
/gate/Kill_BackPlane/geometry/setYLength           30 cm
/gate/Kill_BackPlane/geometry/setZLength           1 nm
/gate/Kill_BackPlane/placement/setTranslation      0.0 0.0 480 mm
/gate/Kill_BackPlane/vis/setColor                  red
/gate/Kill_BackPlane/vis/setVisible                1

/gate/world/daughters/name                   Kill_FrontPlane
/gate/world/daughters/insert                 box
/gate/Kill_FrontPlane/setMaterial                   Air	
/gate/Kill_FrontPlane/geometry/setXLength           30 cm
/gate/Kill_FrontPlane/geometry/setYLength           30 cm
/gate/Kill_FrontPlane/geometry/setZLength           1 nm
/gate/Kill_FrontPlane/placement/setTranslation      0.0 0.0 445 mm
/gate/Kill_FrontPlane/vis/setColor                  red
/gate/Kill_FrontPlane/vis/setVisible                1

/gate/world/daughters/name         grating_foil
/gate/world/daughters/insert       box
/gate/grating_foil/setMaterial                  {grating_material}
/gate/grating_foil/geometry/setXLength          250.0 mm
/gate/grating_foil/geometry/setYLength          250.0 mm
/gate/grating_foil/geometry/setZLength          {foil_thick_um} um
/gate/grating_foil/placement/setTranslation     0 0 {foil_z_um} um
/gate/grating_foil/vis/setVisible               1
/gate/grating_foil/vis/setColor                 grey
/gate/grating_foil/vis/forceSolid

/gate/world/daughters/name         top_pass
/gate/world/daughters/insert       box
/gate/top_pass/setMaterial                  Passivation
/gate/top_pass/geometry/setXLength          250.0 mm
/gate/top_pass/geometry/setYLength          250.0 mm
/gate/top_pass/geometry/setZLength          0.01 mm
/gate/top_pass/placement/setTranslation     0 0 {pass_z_um} um
/gate/top_pass/vis/setVisible               1
/gate/top_pass/vis/setColor                 grey
/gate/top_pass/vis/forceSolid

/gate/world/daughters/name         epi
/gate/world/daughters/insert       box
/gate/epi/setMaterial                  Silicon
/gate/epi/geometry/setXLength          250.0 mm
/gate/epi/geometry/setYLength          250.0 mm
/gate/epi/geometry/setZLength          0.01 mm
/gate/epi/placement/setTranslation     0 0 {epi_z_um} um
/gate/epi/vis/setVisible               1
/gate/epi/vis/setColor                 grey
/gate/epi/vis/forceSolid

/gate/world/daughters/name         bulk
/gate/world/daughters/insert       box
/gate/bulk/setMaterial                  Silicon
/gate/bulk/geometry/setXLength          250.0 mm
/gate/bulk/geometry/setYLength          250.0 mm
/gate/bulk/geometry/setZLength          0.7 mm
/gate/bulk/placement/setTranslation     0 0 {bulk_z_um} um
/gate/bulk/vis/setVisible               1
/gate/bulk/vis/setColor                 blue
/gate/bulk/vis/forceSolid

/gate/world/daughters/name         peak_air_box 
/gate/world/daughters/insert       box 
/gate/peak_air_box/setMaterial                  Air 
/gate/peak_air_box/geometry/setXLength          200.0 mm 
/gate/peak_air_box/geometry/setYLength          200.0 mm 
/gate/peak_air_box/geometry/setZLength          1 mm 
/gate/peak_air_box/placement/setTranslation     0 0 470.5 mm
/gate/peak_air_box/vis/setVisible               1 
/gate/peak_air_box/vis/setColor                 cyan
/gate/peak_air_box/vis/forceWireframe


# /gate/world/daughters/name         PSlayer1 
# /gate/world/daughters/insert       box 
# /gate/PSlayer1/setMaterial                  Silicon 
# /gate/PSlayer1/geometry/setXLength          11.0 mm 
# /gate/PSlayer1/geometry/setYLength          11.0 mm 
# /gate/PSlayer1/geometry/setZLength          10.0 nm 
# /gate/PSlayer1/placement/setTranslation     0 0 450000005.0 nm 
# /gate/PSlayer1/vis/setVisible               1 
# /gate/PSlayer1/vis/setColor                 blue
# /gate/PSlayer1/vis/forceSolid

# /gate/world/daughters/name         peak_air_box 
# /gate/world/daughters/insert       box 
# /gate/peak_air_box/setMaterial                  Air 
# /gate/peak_air_box/geometry/setXLength          180.0 mm 
# /gate/peak_air_box/geometry/setYLength          180.0 mm 
# /gate/peak_air_box/geometry/setZLength          11 mm 
# /gate/peak_air_box/placement/setTranslation     0 0 455.5 mm
# /gate/peak_air_box/vis/setVisible               1 
# /gate/peak_air_box/vis/setColor                 green
# /gate/peak_air_box/vis/forceWireframe

# /gate/peak_air_box/daughters/name         peakLayer1 
# /gate/peak_air_box/daughters/insert       box 
# /gate/peakLayer1/setMaterial                  {peak_material} 
# /gate/peakLayer1/geometry/setXLength          5.0 mm 
# /gate/peakLayer1/geometry/setYLength          5.0 mm 
# /gate/peakLayer1/geometry/setZLength          {peakzlength_um} um 
# #50.0
# /gate/peakLayer1/placement/setTranslation     0 0 {peakztrans_mm} mm
# #450.025 mm 
# /gate/peakLayer1/vis/setVisible               1 
# /gate/peakLayer1/vis/setColor                 grey
# /gate/peakLayer1/vis/forceSolid

# /gate/peak_air_box/daughters/name         lightcover 
# /gate/peak_air_box/daughters/insert       box 
# /gate/lightcover/setMaterial                  {lightcover_material} 
# /gate/lightcover/geometry/setXLength          100.0 mm 
# /gate/lightcover/geometry/setYLength          100.0 mm 
# /gate/lightcover/geometry/setZLength          {lightcoverzlength_um} um
# #200 um  
# /gate/lightcover/placement/setTranslation     0 0 {lightcoverztrans_mm} mm
# #465.525 mm 
# /gate/lightcover/vis/setVisible               1 
# /gate/lightcover/vis/setColor                 magenta
# /gate/lightcover/vis/forceWireframe
# =====================================================
# PHYSICS
# =====================================================

/gate/physics/addPhysicsList emstandard_opt4

/gate/physics/Gamma/SetCutInRegion      world 1 mm
/gate/physics/Electron/SetCutInRegion   world 1 mm
/gate/physics/Positron/SetCutInRegion   world 1 mm

/gate/physics/Gamma/SetCutInRegion      grating_foil 0.00001 mm
/gate/physics/Electron/SetCutInRegion   grating_foil 0.00001 mm
/gate/physics/Positron/SetCutInRegion   grating_foil 0.00001 mm

/gate/physics/Gamma/SetCutInRegion      top_pass 0.00001 mm
/gate/physics/Electron/SetCutInRegion   top_pass 0.00001 mm
/gate/physics/Positron/SetCutInRegion   top_pass 0.00001 mm

/gate/physics/Gamma/SetCutInRegion      epi 0.00001 mm
/gate/physics/Electron/SetCutInRegion   epi 0.00001 mm
/gate/physics/Positron/SetCutInRegion   epi 0.00001 mm

/gate/physics/Gamma/SetCutInRegion      bulk 0.00001 mm
/gate/physics/Electron/SetCutInRegion   bulk 0.00001 mm
/gate/physics/Positron/SetCutInRegion   bulk 0.00001 mm

/gate/physics/Gamma/SetCutInRegion      peak_air_box 0.0001 mm
/gate/physics/Electron/SetCutInRegion   peak_air_box 0.0001 mm
/gate/physics/Positron/SetCutInRegion   peak_air_box 0.0001 mm

# /gate/physics/Gamma/SetCutInRegion      peakLayer1 0.0001 mm
# /gate/physics/Electron/SetCutInRegion   peakLayer1 0.0001 mm
# /gate/physics/Positron/SetCutInRegion   peakLayer1 0.0001 mm

# /gate/physics/Gamma/SetCutInRegion      lightcover 0.0001 mm
# /gate/physics/Electron/SetCutInRegion   lightcover 0.0001 mm
# /gate/physics/Positron/SetCutInRegion   lightcover 0.0001 mm
#=====================================================
# DETECTORS
#=====================================================

# ----------------------------------------------------
# Phase space storage (a PhS for gamma, another for e-)

# /gate/actor/addActor                         PhaseSpaceActor PhS_g
# /gate/actor/PhS_g/attachTo                   PSlayer1
# /gate/actor/PhS_g/save 	                   /work/lb8075/PhaseSpaces/PhS3GammaFromGamma/output-lana3n1-PhS-g.root
# /gate/actor/PhS_g/enableParticleName         false
# /gate/actor/PhS_g/enableProductionVolume     false
# /gate/actor/PhS_g/enableProductionProcess    false
# /gate/actor/PhS_g/useVolumeFrame             true
# /gate/actor/PhS_g/addFilter                  particleFilter
# /gate/actor/PhS_g/particleFilter/addParticle gamma
# /gate/actor/PhS_g/enableZPosition            true

# /gate/actor/addActor                         PhaseSpaceActor PhS_e
# /gate/actor/PhS_e/attachTo                   PSlayer1
# /gate/actor/PhS_e/save 	                   /work/lb8075/PhaseSpaces/PhS3ElecFromGamma/output-lana3n1-PhS-e_nobias{id}.root
# /gate/actor/PhS_e/enableParticleName         false
# /gate/actor/PhS_e/enableProductionVolume     false
# /gate/actor/PhS_e/enableProductionProcess    false
# /gate/actor/PhS_e/useVolumeFrame             true
# /gate/actor/PhS_e/addFilter                  particleFilter
# /gate/actor/PhS_e/particleFilter/addParticle e-
# /gate/actor/PhS_e/particleFilter/addParticle e+
# /gate/actor/PhS_e/enableZPosition            true

## 
## Dose output electron
## 
/gate/actor/addActor                               DoseActor  doseDistribution
/gate/actor/doseDistribution/save                  {pathOutputDose}/Epi-{foil_thick_um}_um_{grating_material}-{id}.root
#/work/lb8075/PhaseSpaces/PhS3DoseFromGamma_50um_plastic1cm/Epi-30mm-no-bias{id}.root
/gate/actor/doseDistribution/attachTo              epi
/gate/actor/doseDistribution/stepHitType           random
/gate/actor/doseDistribution/setPosition           0 0 0 cm
/gate/actor/doseDistribution/setSize               250 250 0.010 mm
/gate/actor/doseDistribution/setResolution         250 250 1	 #for 60 micron pixel x4
/gate/actor/doseDistribution/enableNumberOfHits    true
/gate/actor/doseDistribution/enableEdep            true
/gate/actor/doseDistribution/enableUncertaintyEdep false
/gate/actor/doseDistribution/enableSquaredEdep     true
/gate/actor/doseDistribution/enableDose            false
/gate/actor/doseDistribution/enableUncertaintyDose false


/gate/actor/addActor   KillActor                         Kill_BP 
/gate/actor/Kill_BP/attachTo                             Kill_BackPlane 

/gate/actor/addActor   KillActor                         Kill_FP 
/gate/actor/Kill_FP/attachTo                             Kill_FrontPlane 

#=====================================================
# INITIALISATION
#=====================================================

/gate/run/initialize
# /process/em/setBiasingFactor compt 100 True

# /process/em/setSecBiasing compt peakLayer1 100 1000 MeV
# /particle/process/dump

#=====================================================
# BEAMS
#=====================================================

# Read from Phase Space files. Here we indicate the type of particle
# (gamma) because this information is not stored in the PhS to gain
# space. Moreover, we set 'useRandomSymmetry' to generate more
# particle than the number of particle in the PhS, using a Z axis
# symmetry.

/gate/source/addSource                         beam_g phaseSpace
/gate/source/beam_g/addPhaseSpaceFile          {inputPhaseSpaceFile}_{id}_file1.root
/gate/source/beam_g/addPhaseSpaceFile          {inputPhaseSpaceFile}_{id}_file2.root
/gate/source/beam_g/addPhaseSpaceFile          {inputPhaseSpaceFile}_{id}_file3.root
/gate/source/beam_g/addPhaseSpaceFile          {inputPhaseSpaceFile}_{id}_file4.root
/gate/source/beam_g/addPhaseSpaceFile          {inputPhaseSpaceFile}_{id}_file5.root
/gate/source/beam_g/addPhaseSpaceFile          {inputPhaseSpaceFile}_{id}_file6.root
/gate/source/beam_g/addPhaseSpaceFile          {inputPhaseSpaceFile}_{id}_file7.root
/gate/source/beam_g/addPhaseSpaceFile          {inputPhaseSpaceFile}_{id}_file8.root
/gate/source/beam_g/addPhaseSpaceFile          {inputPhaseSpaceFile}_{id}_file9.root
/gate/source/beam_g/addPhaseSpaceFile          {inputPhaseSpaceFile}_{id}_file10.root
#{inputParticleType}
/gate/source/beam_g/attachTo                   PhS_Plane_Two
/gate/source/beam_g/useRandomSymmetry          true


#=====================================================
# START BEAMS
#=====================================================

/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed {seed}
#1234567890
/gate/application/noGlobalOutput

#/tracking/verbose 2

/gate/application/setTotalNumberOfPrimaries {primaries}
#1000
/gate/application/start


# /gate/physics/processList Enabled
# /gate/physics/processList Initialized

