#=====================================================
#Testing PET things for gate users list

#=====================================================

# VISUALISATION
#=====================================================

# /control/execute visu.mac

# =====================================================
# GEOMETRY
# =====================================================

/gate/geometry/setMaterialDatabase GateMaterialsMac.db

/gate/world/setMaterial            Air
/gate/world/geometry/setXLength    1 m
/gate/world/geometry/setYLength    1 m
/gate/world/geometry/setZLength    2.5 m

/gate/world/daughters/name                   things
/gate/world/daughters/insert                 box
/gate/things/setMaterial              Water
/gate/things/geometry/setXLength      10 cm
/gate/things/geometry/setYLength      10 cm
/gate/things/geometry/setZLength      10 cm
/gate/things/placement/setTranslation 0.0 0.0 0 mm #(-529)
/gate/things/vis/setColor             cyan
/gate/things/vis/setVisible           1

#Physics
/gate/physics/addPhysicsList emstandard_opt3

#Actor
/gate/actor/addActor                               DoseActor  doseDistribution
/gate/actor/doseDistribution/save                  PetDose.root
/gate/actor/doseDistribution/attachTo              things
/gate/actor/doseDistribution/stepHitType           random
/gate/actor/doseDistribution/setPosition           0 0 0 cm
/gate/actor/doseDistribution/setSize               100 100 100 mm
/gate/actor/doseDistribution/setResolution         20 20 20	 
/gate/actor/doseDistribution/enableNumberOfHits    false
/gate/actor/doseDistribution/enableEdep            true
/gate/actor/doseDistribution/enableUncertaintyEdep false
/gate/actor/doseDistribution/enableSquaredEdep     false
/gate/actor/doseDistribution/enableDose            false
/gate/actor/doseDistribution/enableUncertaintyDose false

#=====================================================
# INITIALISATION
#=====================================================

/gate/run/initialize

#====================================================
# BEAMS
#=====================================================

/gate/source/addSource PBS PencilBeam
/gate/source/PBS/setParticleType proton
/gate/source/PBS/setEnergy 188.0 MeV
/gate/source/PBS/setSigmaEnergy 1.0 MeV
/gate/source/PBS/setPosition 0 0 0 mm
/gate/source/PBS/setSigmaX 2 mm
/gate/source/PBS/setSigmaY 4 mm
/gate/source/PBS/setSigmaTheta 3.3 mrad
/gate/source/PBS/setSigmaPhi 3.8 mrad
/gate/source/PBS/setEllipseXThetaEmittance 15 mm*mrad
/gate/source/PBS/setEllipseXThetaRotationNorm negative
/gate/source/PBS/setEllipseYPhiEmittance 20 mm*mrad
/gate/source/PBS/setEllipseYPhiRotationNorm negative
/gate/source/PBS/setRotationAxis 1 0 0
/gate/source/PBS/setRotationAngle 90 deg

#=====================================================
# START BEAMS
#=====================================================

/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed 123456
/gate/application/noGlobalOutput

/gate/application/setTotalNumberOfPrimaries 10
/gate/application/start

