
#=====================================================
# VERBOSITY
#=====================================================

/control/execute mac/verbose.mac

#=====================================================
# VISUALISATION
#=====================================================

# /control/execute mac/visu.mac

# =====================================================
# GEOMETRY
# =====================================================

/gate/geometry/setMaterialDatabase GateMaterials.db

# WORLD
/gate/world/setMaterial            Air
/gate/world/geometry/setXLength    0.80 m
/gate/world/geometry/setYLength    0.80 m
/gate/world/geometry/setZLength    2.1 m
/gate/world/vis/setVisible 1


# VIRTUAL PLANE FOR PHASE SPACE
# It should be the same geometry than PhS generation Here we add a
# "gantry" rotation. To do that easily, we define two box, on for the
# rotation (according to the isocenter=world origin), then one another
# to translation the phase-space plane to the right distance

# /gate/world/daughters/name                     linacGantry
# /gate/world/daughters/insert                   box
# /gate/linacGantry/setMaterial                  Air
# /gate/linacGantry/geometry/setXLength          1.0 mm
# /gate/linacGantry/geometry/setYLength          1.0 mm
# /gate/linacGantry/geometry/setZLength          1.0 mm
# /gate/linacGantry/placement/setRotationAxis    0 1 0
# /gate/linacGantry/placement/setRotationAngle   0 deg
# /gate/linacGantry/vis/setVisible               1

# /gate/linacGantry/daughters/name         linac
# /gate/linacGantry/daughters/insert       box
# /gate/linac/setMaterial                  Air
# /gate/linac/geometry/setXLength          1.0 mm
# /gate/linac/geometry/setYLength          1.0 mm
# /gate/linac/geometry/setZLength          1.0 mm
# /gate/linac/placement/setTranslation     0 0 1000 mm
# /gate/linac/vis/setVisible               1


# /gate/geometry/setMaterialDatabase data/PreciseMaterials.db
# /control/execute mac/linac_head.mac
# /gate/linac/placement/setTranslation 0 0 1000 mm

/gate/world/daughters/name                   PhS_Plane_Two
/gate/world/daughters/insert                 box
/gate/PhS_Plane_Two/setMaterial              Vacuum
/gate/PhS_Plane_Two/geometry/setXLength      15 cm
/gate/PhS_Plane_Two/geometry/setYLength      15 cm
/gate/PhS_Plane_Two/geometry/setZLength      1 nm
/gate/PhS_Plane_Two/placement/setTranslation 0.0 0.0 471 mm #(-529)
/gate/PhS_Plane_Two/vis/setColor             cyan
/gate/PhS_Plane_Two/vis/setVisible           1


/gate/world/daughters/name                   Kill_BackPlane
/gate/world/daughters/insert                 box
/gate/Kill_BackPlane/setMaterial                   Air	
/gate/Kill_BackPlane/geometry/setXLength           80 cm
/gate/Kill_BackPlane/geometry/setYLength           80 cm
/gate/Kill_BackPlane/geometry/setZLength           1 nm
/gate/Kill_BackPlane/placement/setTranslation      0.0 0.0 448 mm
/gate/Kill_BackPlane/vis/setColor                  red
/gate/Kill_BackPlane/vis/setVisible                1

/gate/world/daughters/name                   Kill_FrontPlane
/gate/world/daughters/insert                 box
/gate/Kill_FrontPlane/setMaterial                   Air	
/gate/Kill_FrontPlane/geometry/setXLength           80 cm
/gate/Kill_FrontPlane/geometry/setYLength           80 cm
/gate/Kill_FrontPlane/geometry/setZLength           1 nm
/gate/Kill_FrontPlane/placement/setTranslation      0.0 0.0 475 mm
/gate/Kill_FrontPlane/vis/setColor                  red
/gate/Kill_FrontPlane/vis/setVisible                1

/gate/world/daughters/name         epi
/gate/world/daughters/insert       box
/gate/epi/setMaterial                  Silicon
/gate/epi/geometry/setXLength          10.0 mm
/gate/epi/geometry/setYLength          10.0 mm
/gate/epi/geometry/setZLength          0.01 mm
/gate/epi/placement/setTranslation     0 0 449.995 mm
/gate/epi/vis/setVisible               1
/gate/epi/vis/setColor                 red
/gate/epi/vis/forceSolid

/gate/world/daughters/name         bulk
/gate/world/daughters/insert       box
/gate/bulk/setMaterial                  Silicon
/gate/bulk/geometry/setXLength          10.0 mm
/gate/bulk/geometry/setYLength          10.0 mm
/gate/bulk/geometry/setZLength          0.6 mm
/gate/bulk/placement/setTranslation     0 0 449.69 mm
/gate/bulk/vis/setVisible               1
/gate/bulk/vis/setColor                 yellow

/gate/world/daughters/name         PSlayer1 
/gate/world/daughters/insert       box 
/gate/PSlayer1/setMaterial                  Silicon 
/gate/PSlayer1/geometry/setXLength          10.0 mm 
/gate/PSlayer1/geometry/setYLength          10.0 mm 
/gate/PSlayer1/geometry/setZLength          10000.0 nm 
/gate/PSlayer1/placement/setTranslation     0 0 450005000.0 nm 
/gate/PSlayer1/vis/setVisible               1 
/gate/PSlayer1/vis/setColor                 blue
/gate/PSlayer1/vis/forceSolid

/gate/world/daughters/name         peakLayer1 
/gate/world/daughters/insert       box 
/gate/peakLayer1/setMaterial                  Silicon 
/gate/peakLayer1/geometry/setXLength          5.0 mm 
/gate/peakLayer1/geometry/setYLength          5.0 mm 
/gate/peakLayer1/geometry/setZLength          1000000.0 nm 
/gate/peakLayer1/placement/setTranslation     0 0 450510000.0 nm 
/gate/peakLayer1/vis/setVisible               1 
/gate/peakLayer1/vis/setColor                 grey
# /gate/peakLayer1/vis/forceSolid

# =====================================================
# PHYSICS
# =====================================================

/gate/physics/addPhysicsList emstandard_opt3

/gate/physics/Gamma/SetCutInRegion      world 1 mm
/gate/physics/Electron/SetCutInRegion   world 1 mm
/gate/physics/Positron/SetCutInRegion   world 1 mm

/gate/physics/Gamma/SetCutInRegion      epi 0.0001 mm
/gate/physics/Electron/SetCutInRegion   epi 0.0001 mm
/gate/physics/Positron/SetCutInRegion   epi 0.0001 mm


/gate/physics/Gamma/SetCutInRegion      peakLayer1 0.0001 mm
/gate/physics/Electron/SetCutInRegion   peakLayer1 0.0001 mm
/gate/physics/Positron/SetCutInRegion   peakLayer1 0.0001 mm

# /gate/physics/addProcess Compton
# /gate/physics/processes/Compton/setModel StandardModel gamma
# /gate/physics/processes/Compton/activateSplitting gamma 50

#=====================================================
# DETECTORS
#=====================================================

# ----------------------------------------------------
# the following actor regularly store the current number of
# event/track/step in a file

# /gate/actor/addActor               SimulationStatisticActor stat
# /gate/actor/stat/save              output-readPhS-stat.txt
# /gate/actor/stat/saveEveryNSeconds 10

# ----------------------------------------------------
# the following actor stores 3D Dose/Edep distributions

# ----------------------------------------------------
# Phase space storage (a PhS for gamma, another for e-)

/gate/actor/addActor                         PhaseSpaceActor PhS_g
/gate/actor/PhS_g/attachTo                   PSlayer1
/gate/actor/PhS_g/save 	                     output-lana3n1-PS1ge-5x5-PhS-g.root
/gate/actor/PhS_g/enableParticleName         false
/gate/actor/PhS_g/enableProductionVolume     false
/gate/actor/PhS_g/enableProductionProcess    false
/gate/actor/PhS_g/useVolumeFrame             true
/gate/actor/PhS_g/addFilter                  particleFilter
/gate/actor/PhS_g/particleFilter/addParticle gamma
/gate/actor/PhS_g/enableZPosition            true
# #/gate/actor/PhS_g/saveEveryNSeconds          20

/gate/actor/addActor                         PhaseSpaceActor PhS_e
/gate/actor/PhS_e/attachTo                   PSlayer1
/gate/actor/PhS_e/save 	                     output-lana3n1-PS1ge-5x5-PhS-e.root
/gate/actor/PhS_e/enableParticleName         false
/gate/actor/PhS_e/enableProductionVolume     false
/gate/actor/PhS_e/enableProductionProcess    false
/gate/actor/PhS_e/useVolumeFrame             true
/gate/actor/PhS_e/addFilter                  particleFilter
/gate/actor/PhS_e/particleFilter/addParticle e-
/gate/actor/PhS_e/particleFilter/addParticle e+
/gate/actor/PhS_e/enableZPosition            true
# /gate/actor/PhS_e/saveEveryNSeconds          20


## 
## Dose output electron
## 
# /gate/actor/addActor                               DoseActor  doseDistribution
# /gate/actor/doseDistribution/save                  Epi.root
# /gate/actor/doseDistribution/attachTo              peakLayer1
# /gate/actor/doseDistribution/stepHitType           random
# /gate/actor/doseDistribution/setPosition           0 0 0 cm
# /gate/actor/doseDistribution/setSize               10 10 0.010 mm
# /gate/actor/doseDistribution/setResolution         200 200 1	 #for 60 micron pixel x4
# /gate/actor/doseDistribution/enableNumberOfHits    true
# /gate/actor/doseDistribution/enableEdep            true
# /gate/actor/doseDistribution/enableUncertaintyEdep false
# /gate/actor/doseDistribution/enableSquaredEdep     true
# /gate/actor/doseDistribution/enableDose            false
# /gate/actor/doseDistribution/enableUncertaintyDose false

/gate/actor/addActor                               DoseActor  doseDistribution
/gate/actor/doseDistribution/save                  epi_5x5_ge.root
/gate/actor/doseDistribution/attachTo              bulk
/gate/actor/doseDistribution/stepHitType           random
/gate/actor/doseDistribution/setPosition           0 0 0 cm
/gate/actor/doseDistribution/setSize               10 10 0.010 mm
/gate/actor/doseDistribution/setResolution         200 200 2 #for 60 micron pixel x4
/gate/actor/doseDistribution/enableEdep            true
/gate/actor/doseDistribution/enableUncertaintyEdep false
/gate/actor/doseDistribution/enableDose            false
/gate/actor/doseDistribution/enableUncertaintyDose false
/gate/actor/doseDistribution/enableNumberOfHits    true


/gate/actor/addActor   KillActor                         Kill_BP 
# /gate/actor/Kill_BP/save                                 MyOutputFile7.txt
/gate/actor/Kill_BP/attachTo                             Kill_BackPlane 

/gate/actor/addActor   KillActor                         Kill_FP 
# /gate/actor/Kill_FP/save                                 MyOutputFile8.txt
/gate/actor/Kill_FP/attachTo                             Kill_FrontPlane 

#=====================================================
# INITIALISATION
#=====================================================

/gate/run/initialize

# /process/em/setSecBiasing compt world 100 100 MeV
# /process/em/setSecBiasing compt mlc_leaf 100 100 MeV
# /process/em/setSecBiasing compt jaw_y1 100 100 MeV
# /process/em/setSecBiasing compt jaw_y2 100 100 MeV
# /process/em/setSecBiasing compt jaw_x1 100 100 MeV
# /process/em/setSecBiasing compt jaw_x2 100 100 MeV
#=====================================================
# BEAMS
#=====================================================

# Read from Phase Space files. Here we indicate the type of particle
# (gamma) because this information is not stored in the PhS to gain
# space. Moreover, we set 'useRandomSymmetry' to generate more
# particle than the number of particle in the PhS, using a Z axis
# symmetry.

/gate/source/addSource                         beam_g phaseSpace
/gate/source/beam_g/addPhaseSpaceFile          PhS2_20x20/SkimmedSubArea/Skimmed50x50mm-From20x20cm-PhS2-e-Total.root
/gate/source/beam_g/setParticleType            e-
/gate/source/beam_g/attachTo                   PhS_Plane_Two
/gate/source/beam_g/useRandomSymmetry          true


#=====================================================
# START BEAMS
#=====================================================

/gate/random/setEngineName MersenneTwister
/gate/random/setEngineSeed auto
/gate/application/noGlobalOutput

#/tracking/verbose 2

/gate/application/setTotalNumberOfPrimaries 9352518
/gate/application/start


# /gate/physics/processList Enabled
# /gate/physics/processList Initialized
